### ISSUE TITLE
--output-format=dot and datasource choice

### ISSUE THREAD

**Issue by maieul** [plk/biber#110]
Hi,

the --output-format=dot is very useful to documente the data inheritance mechanism of biblatex/biber, especilally when creating new field / entry type. Cf for example the [biblatex-bookinarticle handbook](http://mirrors.ctan.org/macros/latex/contrib/biblatex-contrib/biblatex-bookinarticle/documentation/biblatex-bookinarticle.pdf).

Hoewever, should it be possible to have an option to specify we would like to produce the graph only for one datasource. For example in http://ctan.org/tex-archive/macros/latex/contrib/biblatex-contrib/biblatex-bookinarticle/documentation, in would like to obtain one .dot file for each .bib file, and not one global file.

**Comment by plk** [comment]
That's a bit tricky because one thing the DOT output format does is to show relations between entries and there could be relations (RELATED, XDATA, CROSSREF, SET etc.) between entries in different datasources.  You could just make a dummy file with one `\notecite{*}` and comment out all but one of the `\addbibresource` macros to make one `.dot` file per datasource? This could easily be automated as part of a build/make script.

**Comment by maieul** [comment]
Hi, 

thans for your quick answer. I was not thinking people could use related entry between multiple datasources. In is not very safe for the integrity of the data.

I have thought to your solution. But I was thinking a low level solution would be more logical. But if you say it is too hard, I would do that.

**Comment by plk** [comment]
I think it's not that unlikely that someone might split datasources into sets/members, related entries, xdata elements ...

**Comment by maieul** [comment]
yes, maybe, I don't know. However, for this specific issue, that is not related. But I will do a script.

**Comment by maieul** [comment]
for your information, if needed https://git.framasoft.org/maieul/biblatex-morenames/blob/master/documentation/generate-crossref-graphs.py
