### ISSUE TITLE
Biber in tool mode strips custom fields and converts "year" to "date"

### ISSUE THREAD

**Issue by ClaudiusL** [plk/biber#146]
Biber in tool mode strips custom fields (example: `owner`) and turns `year` fields into `date` fields.

Not sure if this is a bug or intended, but as it changed from version 2.5 and 2.6 without any comment in the changelog I'm surprised.

Example:

**`testbib.bib`**:

```
@REPORT{Self2016,
  YEAR		= {2016},
  AUTHOR    = {Self, My},
  TITLE     = {The title},
  OWNER		= {Me}
}
```
Output of `biber --tool --output_file out.bib testbib.bib`:

**With biber 2.5:**

```
@REPORT{Self2016,
  AUTHOR = {Self, My},
  OWNER = {Me},
  TITLE = {The title},
  YEAR = {2016},
}
```

**With biber 2.6:**

```
@REPORT{Self2016,
  AUTHOR = {Self, My},
  DATE = {2016},
  TITLE = {The title},
}
```

Is this intended? If yes, is there a command line option to emulate the old behavior?

**Comment by plk** [comment]
Hmm, the `YEAR` -> `DATE` is expected as tool mode with bibtex output now goes via the data model and `YEAR` is deprecated due to the significantly enhanced EDTF date handling in biblatex 3.5+. The dropping of unknown fields is because such fields do not exist in the data model and tool mode with bibtex output now uses the data model. This should have been documented really, I agree. I will update the biber PDF doc for 2.7. To preserve custom fields, they should be defined in the data model in the `biber-tool.conf` file. The location of the default conf file can be found with `biber --tool-conf` which can then be copied/consulted to create a custom config file whose settings will override the master config file. You can also ask on tex.stackexchange.com about this.

**Comment by ClaudiusL** [comment]
Thank you for the feedback, @plk. I think that I successfully extended the data model, but maybe you could help me understand better what I've done [here](http://tex.stackexchange.com/q/333794/37118).

Regarding the `Year`->`Date` conversion: Ok, I see why this makes sense. This will result in a quite messy commit on my version controlled BIB file …
