### ISSUE TITLE
Throws error on tick character in key

### ISSUE THREAD

**Issue by karyon** [plk/biber#154]
in this bib entry:

```
@article{vCad'ik-2008,
  author = {Martin \v{C}ad\'ik},
  title = {Perceptual Evaluation of Color-to-Grayscale Image Conversions},
  journal = {Comput. Graph. Forum},
  year = {2008},
  volume = {27},
  pages = {1745-1754},
  number = {7}
}
```

biber throws the following error:

```
[403] Utils.pm:180> ERROR - BibTeX subsystem: C:\Users\Username\AppData\Local\Temp\PglhOC87mF\foo-thesis.bib_6388.utf8, line 4, syntax error: found "k-2008", expected ","
```

it's easy to fix by removing the `'` character from the key. i just was wondering whether this might be a bug because it works when using bibtex.

**Comment by plk** [comment]
This is one of the minor differences between bibtex and the btparse library used by biber. I am loathe to hack the ancient parser used by btparse any more, unless there is a real need and since this is the first time this particular issue has been raised, I'm inclined to recommend editing the key ...

**Comment by karyon** [comment]
not going to argue against this :) personally i have no reason to not change the key.
