### ISSUE TITLE
wrong version on SF

### ISSUE THREAD

**Issue by thymaro** [plk/biber#230]
I go to SF and download packaged biber (in my case: for ubuntu 64bit and MSWIN64). Both times, I end up with version 2.10 of biber instead of 2.11. On Windows, I just took the automatic download, so my best guess is that 2.11 is not stored on SF, yet.

**Comment by moewew** [comment]
Mhhh, indeed the "Latest" button leads to the wrong version. @plk Can that be fixed by you or is that some kind of automatic link provided by SourceForge?

For the time being go to the `current` directory directly: https://sourceforge.net/projects/biblatex-biber/files/biblatex-biber/current/binaries/

But as always the advice is not to download Biber from SourceForge unless absolutely necessary. Get the correct version from your TeX distribution instead, that makes sure that `biblatex` and Biber are kept in sync.

**Comment by thymaro** [comment]
Yes, I figured that would be the easiest and also best solution, but then I got those strange error messages. Anyways, I deleted that `par-123456789` directory in `c:/users/thymaro/appdata/local/temp/`, then ran `biber --version` again, it produced the par-... folder again, but then output biber 2.11. So, all is well, I guess.

**Comment by plk** [comment]
Fixed on SF - for some reason, some platforms were not pointing to the latest versions.

**Comment by moewew** [comment]
Thank you. In a quick test just moments ago the link worked correctly for WIN64.
