### ISSUE TITLE
File::Slurper::write_text failed

### ISSUE THREAD

**Issue by spl** [plk/biber#239]
In the process of testing my `biber` build and installation, I tried a source file `t/tdata/full-bbl.bcf`, but it failed at https://github.com/plk/biber/blob/8ebedab/lib/Biber.pm#L323 which contains:

```perl
# Write ctrl file as UTF-8
File::Slurper::write_text($ctrl_file_path, NFC($checkbuf));# Unicode NFC boundary
```

The files were in a remote directory. If I copied `full-bbl.bcf` and `full-bbl.bib` locally, `biber` succeeded. I'm guessing there is some permission issue either with the files or the directory.

What is `$ctrl_file_path` here? Is it `full-bbl.bcf`? If so, I don't think it's a good idea to be writing to it. In general, one would not expect a source file to be updated, even if the update is benign. A warning would be better.

**Comment by plk** [comment]
Hmm, yes, `$ctrl_file_path` is the .bcf and is written to normalise to to UTF-8 in case of malformed edge cases. Since the `.bcf` is an intermediate auto-generated file (by `biblatex`), this isn't really a problem. It sounds like OS/filesystem permission issues?

**Comment by spl** [comment]
Thanks for the info!

> Hmm, yes, `$ctrl_file_path` is the .bcf and is written to normalise to to UTF-8 in case of malformed edge cases. Since the `.bcf` is an intermediate auto-generated file (by `biblatex`), this isn't really a problem.

I guess if you consider `biber` as part of the `biblatex` system, that might be fine. But if `biblatex` is generating the file, why would it be malformed? Could this be hiding some other bug?

> It sounds like OS/filesystem permission issues?

I think it's something Homebrew is doing with installed files, which is how these files are treated until I need to test them. It probably makes them read-only to preserve their integrity. My workaround of copying them is perfectly fine.

I'm more concerned that `biber` is writing to what I would consider an input file. But I guess it all depends on how you look at it.

**Comment by moewew** [comment]
I can understand that it looks odd that Biber would write to the `.bcf` file. After all the idea is that the `.bcf` is written by `biblatex` (LaTeX) to communicate with Biber and that Biber writes the `.bbl` to communicate with `biblatex`. So as far as Biber is concerned the `.bcf` is input and as such would not need writing to.

In practice I guess it does not really matter a great deal since the `.bcf` file is temporary in nature and in general write permission is needed anyway (naively I would have thought it not very plausible that LaTeX should be allowed to write on the file but Biber should be banned from doing that, but why not...).

Now I am curious: In which cases is the additional write needed? And would it be possible not to write to the `.bcf`? It seems to me that Biber managed to read the file correctly even if it has to somehow re-write the `.bcf`. Given that the data is present anyway would it not be possible to just use it without re-writing the `.bcf`? After all LaTeX is going to overwrite the `.bcf` on the next pass anyway (at least in normal use cases), so I'd have thought that we don't win a lot if we write the corrected file out.

**Comment by spl** [comment]
@moewew Well said! I have the same questions.

**Comment by plk** [comment]
This was due to a slightly too generic solution to a very specific issue with .bcfs produced in latin1 and needing recoding to UTF-8. I have changed `biber` 2.13 DEV to only re-write if this specific condition is met.
