### ISSUE TITLE
Required Perl version is overly restrictive

### ISSUE THREAD

**Issue by fmitha** [plk/biber#247]
I'm trying to backport TeX Live from Debian unstable to Debian stable. I've done so successfully - it was actually quite easy and smooth. But Biber has been a thorn in my side, because Biber requires Perl 2.26, and the version in Debian stable is only 2.24. The upshot is that if I want to use Biber on Debain stable, I have to replace 2.24 with 2.26, which I'm not keen to do because of the risk it could break the system. For historical reasons, many Linux distributions, including Debian, depend on Perl for base functionality.

So, what I'm asking is that Biber be more conservative in what version of Perl it requires. It's common practice to be conservative about version requirements for precisely this reason; because systems may not have very recent versions of software of software. And 5.26 was released on May 30, 2017, so it is fairly recent. In doubt, one can check what software Debian stable is running, and possibly also RHEL.

I've run into the situation before, in 2014. See for example, https://chat.stackexchange.com/transcript/41?m=14827099#14827099

I managed to work around it somehow - I don't remember how and unfortunately I didn't make notes; at least I can't discover any now. But  If you have suggestions for how to work around this issue, please let me know. Thank you.

**Comment by plk** [comment]
It's not clear to me, if you are porting TeX Live, why you are having to deal with the perl version at all. Biber is in TeX Live as a packed binary which includes the correct version of perl in its packed form. It doesn't require a perl installation at all unless you are running it as a script from the source. It's not recommended to do this unless you really have to since there are linux packed binaries in TexLive and served by CTAN/tlmgr etc. This is the very reason I allow myself to bump the perl version up and use recent perl features - because almost no-one is using pure-perl script based installations.

**Comment by fmitha** [comment]
HI plk,

Thank you for the fast response. That may explain what I did in 2014 - probably just copied the binary to my local bin, /usr/local/bin, or similar. 

But if Biber doesn't require a Perl installation, can you explain why the Biber Debian package declares a Perl dependency? That's the reason that I'm having to deal with it - because of that dependency. And the Debian build runs tests by default, and those tests are all erroring out, though I'm not clear why. But it is not encouraging. Do you have any interest in failing tests?

**Comment by fmitha** [comment]
Hi plk,

Ok. I disassembled the Debian package and confirmed that the Biber executable contained therein is a Perl script. Are you saying this is not standard practice? The script starts with

```
#!/usr/bin/env perl

use v5.24;
use strict;
use warnings;

use constant {
  EXIT_OK => 0,
  EXIT_ERROR => 2
};
```
and contains the copyright line

    Copyright 2009-2018 François Charette and Philip Kime, all rights reserved.

I'm guessing you are Philip Kime. Is it worth asking the Debian maintainer why he is doing is this way? He seems sensitive and easily offended.

If I download a Linux binary executable from the Biber site and drop it in my local bin directory, would that work? And if the Biber executable is a binary executable, how does the Perl version enter into things? Just curious.

**Comment by dcpurton** [comment]
@plk, this often comes up. The Linux distros *always* ship `biber` as a script, not a packed binary. See for example issue #142. You will find that the Linux distros would rebuild all the binaries that come with TL as well.

This doesn't stop someone using vanilla TeXLive on Linux (package managers are not mandated), but if you want to create packages like the OP does, then the pre-packaged binary is simply not an option.

@fmitha, unless you're building for Debian Backports, I'd give up and use vanilla TeXLive instead of trying to backport the Debian packages.

For reference the Perl 5.26 requirement came in at https://github.com/plk/biber/commit/08181264467024fdcb2ff24a8e2cebf33c6b3755 (which I agree is actually pretty close to the release of 5.26, but a fair while ago now and presumably there was a good reason for needing some feature of 5.26—maybe @plk can explain the reason and you can decide if it's worth patching `biber` to only need 5.24.)

**Comment by fmitha** [comment]
Hi @dcpurton,

Thank you for your comments. First, I'm not building for Debian Backports, though that's not a bad idea. But given the current situation, this isn't an option, anyway. I'm just backporting it for myself. Regardless, I have no plans to switch to vanilla TeX Live. While Norbert Preining continues to package TeX for Debian, I'll continue to use his packages. And I can just download and use the Biber binary from the Biber web site and use it. This is a ugly workaround, but currently it looks like there is no option.

I'm also a little puzzled that there does not seem to be more awareness of Debian here. While Debian is hardly mainstream, it's also not exactly obscure. These days it's almost the longest-lived Linux distribution. And is the basis for many other Linux distributions.

What is the reason why Biber ships in Linux distributions as a script and not a binary? I'm wondering if I should file a Debian bug to ask, because I'm unclear about the reason. Does anyone else know?

And if the distributions are required to ship Biber as a script, then I again ask that some thought be given before bumping Perl versions. As already mentioned, it's standard to be conservative about dependency versions. And in the case of something as old and stable as Perl 5, is it really necessary to stay with a very recent version, anyway?

All of TeX Live seems to be trivial to backport. Biber appears to be one of the few exceptions, and possibly the only exception.

**Comment by dcpurton** [comment]
@fmitha all the Linux distros build from source and do not ship pre-built binaries from upstream. They also have a tendency to try and avoid redundancy in their repositories if possible. Debian supports lots of architectures. To ship `biber` as a binary means to ship a different package for every architecture containing Perl for that architecture. This is unnecessary and redundant. If you look at the official `biber` Debian package you will see that it is the same package for all architectures and just uses the main Perl version installed on the machine. This way if there is a security flaw in Perl, they don't have to patch `biber` on every platform as well.

My observation is that nearly all Linux TeX users use Vanilla TeXLive because they want the latest packages quickly and easily and apart from the rolling Linux distros (Like Debian/Arch, which few people use) you get stuck with old versions of TeXLive for too long.

It *is* possible to have your cake and eat it with Debian, but you have to run Debian Testing (or Unstable). I do this and the version of TeXLive in Debian testing only lags behind by only 1–2 months. I consider this an acceptable cost for the convenience of Debian's superior packaging of TeXLive.

From the point of view of the `biber` developer, maintaining `biber` releases as script only would be a nightmare. There are too many possible combinations of Perl version and Perl module versions to make it feasible.

And finally, although I'm not sure I think the main reason for needing upgrades to Perl and Perl modules is to do with the complex requirements of sort in languages other than English. People find that `biber` doesn't sort properly and that requires updates to the Perl sorting stuff and so `biber` has quite bleeding edge dependencies even though you wouldn't expect it if only English was in use.

**Comment by fmitha** [comment]
@dcpurton Thank you for the detailed answer. 

> It is possible to have your cake and eat it with Debian, but you have to run Debian Testing (or Unstable). 

No, I don't. As already mentioned, backporting is possible, except for Biber, as discussed here. I backported much of TeX Live. Perhaps not all of it, but a lot, and there was no problem. Which makes me wonder what makes Biber special. There are a vast number of packages in TeX Live and they seem to manage without bleeding edge dependencies.

>  To ship biber as a binary means to ship a different package for every architecture containing Perl for that architecture.

Yes, but that's not a problem in itself. Debian builds and distributes different binary packages for each architecture it supports already. That's standard practice. Perhaps the issue is that the Biber binary is analogous to containing an embedded library?

Consider the familiar example of a C program depending on a C library. If there is a security flaw in the library, then it suffices to replace/update/rebuild that library. It's not necessary to rebuild all the programs that depend on that library. In a similar way, Perl scripts don't need to be replaced if there is a security problem with Perl, or it needs to be updated for some other reason. But it sounds like the Biber binary would contain an embedded Perl interpreter, which would indeed be a problem if Perl had a security issue or needed to be updated for some other reason.

**Comment by fmitha** [comment]
Hi @dcpurton,

Normally the language and the supporting libraries are somewhat decoupled. One would expect some sort of loose dependency relationship. For example, with Python, Python 2 libraries typically declare a relationship of >= 2.x, for some x. So one would expect to be able to install more recent libraries without having to upgrade Perl (the language) itself.

**Comment by fmitha** [comment]
@plk UCA presumably refers to Unicode Collation Algorithm. Does this have significant changes between Perl 5.24 and 5.26, and is it part of the Perl 5 core? I'm surprised that Perl 5 is still changing significantly at this late point in its evolution, but perhaps a change in UCA (whatever that is) does not constitute a significant change.

As observed above, Debian indeed using the script version of Biber, and are unlikely to  switch to a binary version.

**Comment by plk** [comment]
The version of base Unicode supported changes with every perl release. The UCA is implemented by `Unicode::Collate` which is a base package too. However, I tend to update that regularly in the packed `biber` as it is so important.

**Comment by cbm755** [comment]
In case its helpful for Debian, In Fedora we did https://src.fedoraproject.org/rpms/biber/c/b0948facef7f63233513713bfeeea57004c2886c?branch=master
which is based on upstream 6b61b4c13778cf638f82569ab9e413f09f111ba5

This is for Unicode::Collate 1.27
