### ISSUE TITLE
[question] .bcf validation & constraints

### ISSUE THREAD

**Issue by Aerijo** [plk/biber#249]
Hi, I'm trying to write a biber linter that's more sophisticated than existing options (and I don't want to use `biber --validate-datamodel` each time I need to lint).

I've found the generated `.bcf` file to hold most / all the information I want, but have a couple of questions about what I can expect from it.

- Is [the schema](https://github.com/plk/biber/blob/dev/data/schemata/bcf.rnc) absolutely followed by all styles? I would think so, but the BibLaTeX documentation suggests it may be extended from [the set types](https://github.com/plk/biber/blob/50f75a3513334a006a952bc2dee6b87e455799ef/data/schemata/bcf.rnc#L857) when it says "typically"
> Set the type of the field as described in § 2.2.1, typically ‘field’ or ‘list’ (p195)

- (I think the above could answer this, but) how complicated can mandatory constraints get? I treat them as either "all", "some", or "one". Is it possible (now or in the future) that it might allow nested conditionals, like
```
some: {
  field: foo,
  one: {
    field: bar,
    field: baz
  }
}
```
I.e., that it requires at least one of `foo`, `bar`, or `baz`, but cannot have both `bar` and `baz` (e.g., `foo` and `bar` would be valid, but not all three)? Or is the correct way always to use conditional constraints?

**Comment by plk** [comment]
- The `.bcf` schema is not style-specific but the contents of a given `.bcf` might be because a style (or even a document) can define its own data model, constraints etc. You can't therefore rely on a particular data model etc. but you can rely on the `.bcf` schema. The `.bcf` is a complete, isolated data interface to `biber`. It only reads the `.bcf` (and via this, the data sources) and only outputs a `.bbl`.
- Yes, conditionals are intended for more complex cases (since given conditionals with quantifiers, nested standard booleans are redundant). It was designed this way because nested mandatory constraints are tedious to implement and are seldom used (I've never seen anyone use them).

-

**Comment by plk** [comment]
Right, currently, the schema mandates only "field" or "list". It is conceivable that the schema could change with future enhancements but in this particular case, it's not likely. For implementing a .bcf parser, you can completely rely on the .`rnc` schema for the latest `biber` release.

**Comment by Aerijo** [comment]
Great, thanks again
