### ISSUE TITLE
Date constraint checking

### ISSUE THREAD

**Issue by Aerijo** [plk/biber#252]
With fields, you [can declare](https://github.com/plk/biber/blob/50f75a3513334a006a952bc2dee6b87e455799ef/data/schemata/bcf.rnc#L298) their `datatype` to be `"date"`. However, you can also place [a constraint](https://github.com/plk/biber/blob/afa6c580bdf599e9aaacbb9df58ae9f468734b46/data/schemata/config.rnc#L218) on a field requiring that the constraint datatype be a `"date"`. 

First, is there a meaningful difference between the field datatype and the constraint datatype being `"date"`? I think it could be used when only certain entries need a field to act like a date, but the default data model explicitly constrains the date fields globally, in addition to setting their field type as "date", which feels redundant. For  the others, like `"isbn"`, it looks like a way to be stricter about the content form (e.g., field type string, constraint type isbn).

Also, it appears the date constraint is [not tested](https://github.com/plk/biber/blob/3f977d9b592e238ed297161a3826901f710bbad3/lib/Biber/DataModel.pm#L753) when validating the data model. I don't know Perl, so I'm kind of skimming and relying on Find and Replace, but is this intentional or a bug? It does check for a `datepart` constraint, but I can't see where `date` get's converted to `datepart`, or how it accounts for this with the constraint.

**Comment by plk** [comment]
The `datatype` is there to tell `biber` how to parse the field. The constraint datatype was a mistake in the docs, it should be `datepart` since dates are already fully parsed by the time valuation occurs. This is corrected in biblatex/biber 3.13/2.13 DEV versions. Also, you might want to get this version anyway as there have been some `.bcf` schema changes there too to support some new options and to correct some issues.
