### ISSUE TITLE
newlines converted to spaces in url entry field

### ISSUE THREAD

**Issue by nicolasmeric** [plk/biber#267]
When using newlines (\n) to split
a long url in an url entry field in a bib file,
every newline character is converted to space in the bbl file.
Indeed, with the following mwe:

```latex
\documentclass{article}

\usepackage[backend=biber]{biblatex}

\addbibresource{\jobname.bib}

\usepackage{filecontents}

\begin{filecontents}{\jobname.bib}
@online{key,
  author = {Wikipédia},
  title = {Fonds monétaire international \textemdash{} Wikipédia,
    l'encyclopédie libre
  },
  date = {2019-05-17},
  langid = {french},
  url = {http://fr.wikipedia.org/w/index.php?
title=Fonds_mon%C3%A9taire_international&oldid=159334561},
  urldate = {2019-05-23},
}
\end{filecontents}

\begin{document}

\cite{key}

 \printbibliography{}

\end{document}
```

we can see that I broke the url with a newline in the mwe,
after the question mark.
biber will convert the newline to space in the bbl file,
and this is not what is expected, at least the way I see it.
It means it is impossible to keep a line length shorter than 80 characters
with very long url in source file.

**Comment by plk** [comment]
This isn't really fixable - a URL is designed to be clickable in documents and so formatting them like this in the .bib isn't really semantically appropriate. I know it's annoying but this is really an editor issue - many editors are customisable to pseudo line break things like this without actually introducing invalid characters into data.

**Comment by nicolasmeric** [comment]
I know about pseudo line breaking.
But it's more about having consistent entry processing.
In my mwe, I can note that the title entry field,
which also includes a newline character, is properly processed,
and the newline character is removed.
Should EOLs characters not be deleted when the url entry field is processed,
in the same way the title entry field is processed, should they ?

**Comment by plk** [comment]
The problem is that `url` is a verbatim field which are never modified by design. However, you will see in the `.bbl` that this only impact the `urlraw` field and not the `url` field itself which should be be properly URL encoded.

If you really want to change this, they you could redefine url as a non-verbatim field in the data model but I suspect that this would lead to more problems.

**Comment by moewew** [comment]
```latex
\documentclass{article}

\usepackage[backend=biber]{biblatex}

\usepackage{filecontents}
\begin{filecontents}{\jobname.bib}
@online{key,
  author = {Wikipédia},
  title = {Fonds
    monétaire 
    international
    \textemdash{}
    Wikipédia, l'encyclopédie libre
  },
  date = {2019-05-17},
  langid = {french},
  url = {http://fr.wikipedia.org/w/
    index.php?
    title=Fonds_mon%C3%A9taire_international
    &oldid=159334561},
  urldate = {2019-05-23},
}
\end{filecontents}
\addbibresource{\jobname.bib}

\begin{document}
\cite{key}
\printbibliography
\end{document}
```
produces
```latex
\field{title}{Fonds monétaire international —{} Wikipédia, l'encyclopédie libre}
\verb{urlraw}
\verb http://fr.wikipedia.org/w/ index.php? title=Fonds_mon%C3%A9taire_international &oldid=159334561
\endverb
\verb{url}
\verb http://fr.wikipedia.org/w/%20index.php?%20title=Fonds_mon%C3%A9taire_international%20&oldid=159334561
\endverb
```
in the `.bbl`. This shows that Biber emulates the behaviour of LaTeX with regard to EOL chars: They are simply treated as a space. Consecutive spaces are run into a single space. (Biber also apparently removes leading and trailing spaces in a field.) This makes good sense for literal fields and the fact that LaTeX behaves the same makes it very natural.

For verbatim/URI fields the behaviour is a bit unfortunate, since the spaces that are introduced by line breaks get converted to `%20`.

Note in particular that the processing of all fields *is* consistent in the sense that all new lines are transformed into spaces and that several spaces are condensed down to one.

Personally, I think there would be some merit in having line breaks in URI fields completely ignored (i.e. not converted to spaces), since that would allow for hard-wrapped `.bib` files, but it stands to reason that this behaviour would in fact *introduce* an inconsistency and I have no idea if it is even possible (does `btparse` do the space thingy?).

---

Compare this with BibTeX's behaviour in
```latex
\documentclass{article}

\usepackage{hyperref}
\usepackage{filecontents}
\begin{filecontents}{\jobname.bib}
@online{key,
  author = {Wikipédia},
  title = {Fonds
    monétaire 
    international
    \textemdash{}
    Wikipédia, l'encyclopédie libre
  },
  date = {2019-05-17},
  langid = {french},
  url = {http://fr.wikipedia.org/w/
    index.php?
    title=Fonds_mon%C3%A9taire_international
    &oldid=159334561},
  urldate = {2019-05-23},
}
\end{filecontents}

\begin{document}
\cite{key}
\bibliographystyle{plainurl}
\bibliography{\jobname}
\end{document}
```
which produces
```latex
\bibitem{key}
Wikipédia.
\newblock Fonds monétaire international \textemdash{} wikipédia,
  l'encyclopédie libre.
\newblock URL: \url{http://fr.wikipedia.org/w/ index.php?
  title=Fonds_mon%C3%A9taire_international &oldid=159334561}.
```
Again, EOL chars are converted to spaces and several spaces are compressed to one space, though this time BibTeX itself introduces some line breaks of its own at spaces (note that the line break introduced by BibTeX need not coincide with a line break in the `.bib` source, every space is eligible for breaking). 

The URL also contains undesirable line breaks and spaces, but `\url` conveniently swallows them so that in the output things look alright (at least if `url` is loaded).

---

FWIW with `backend=bibtex` the first MWE gives
```latex
    \field{title}{Fonds monétaire international \textemdash{} Wikipédia,
  l'encyclopédie libre}
    \verb{url}
    \verb http://fr.wikipedia.org/w/ index.php? title=Fonds_mon%C3%A9taire_inte
    \verb rnational &oldid=159334561
    \endverb
```
in the `.bbl`.

**Comment by plk** [comment]
Unfortunately this newline/space collapsing it done by btparse. I can always strip out any spaces in `uri` field types since this is a specific data type in `biber`. However, that won't work in general as some uris do have spaces in them and are subsequently URI-encoded with `%20` without problem. It's not really possible to tell in `biber` currently which spaces are desired and which aren't, which is sort of the point of verbatim fields ...
