### ISSUE TITLE
custom datamodel and uppercase field names

### ISSUE THREAD

**Issue by dcpurton** [plk/biber#278]
`biber` seems to ignore fields that are declared with upper case field names but this isn't mentioned in the `biblatex` manual.

See https://tex.stackexchange.com/questions/505179/biblatex-custom-fields-are-not-shown

I notice that you can declare an uppercase entry type, e.g., `\DeclareDatamodelEntrytypes{Uftype}
` and then this works provided the driver is lowercase as mentioned in the documentation for `\DeclareBibliographyDriver`.

But for fields, the field is included in the `.bcf` file, but not in the `.bbl` file and there is nothing mentioned in the manual under the `\printfield` documentation as to whether the field name should be upper or lower case (in fact it must be lower case to work).

The manual should be fixed to make this clear and/or `biber` should treat fields in a case insensitive way as it does for entry types. **Edit** Actually I just notice that in the `biber` change log from version 0.9.6 data source entry keys are treated as case sensitive. But this doesn't actually seem to be true. I can declare the entry type with uppercase letters, but the driver must be declared with lowercase letters for it to work.

# MWE

```TeX
\RequirePackage{filecontents}
\begin{filecontents}{ufbibstyle.dbx}
\DeclareDatamodelEntrytypes{Uftype}
\DeclareDatamodelFields[type=field,datatype=literal]{uffielda,uffieldB}
\DeclareDatamodelEntryfields[Uftype]{uffielda,uffieldB}
\end{filecontents}
\begin{filecontents}{ufdbx.bib}
@Uftype{testdbx,
uffielda={A},
uffieldB={B},
titleaddon = {something},
}
\end{filecontents}
\documentclass{article}
\pagestyle{empty}
\usepackage[datamodel=ufbibstyle]{biblatex}
\DeclareBibliographyDriver{uftype}{% 
  \printfield{uffielda},\printfield{uffieldB}}
\addbibresource{ufdbx.bib}
\begin{document}
\cite{testdbx}
\printbibliography
\end{document}
```

**Comment by moewew** [comment]
This is an interesting issue. When it comes to case sensitivity of entry types and input field fields there are two sides involved in `biblatex`: The backend and the LaTeX side.

BibTeX ignores case for both entry types and field names, so it never really mattered what people used in their `.bib` files. But TeX is case sensitive, so when we code the `biblatex` style we need to make sure that the `.bbl` file produced by Biber/BibTeX and our code match.

That's why I always use lowercase everywhere. But I guess it would be expected that uppercase characters should be usable in the datamodel. The question is whether they should be passed to the `.bbl` in the original capitalisation from the `.dbx` or in a normalised all-lowercase version.

Taking this a bit (much?) further, case-folding has its pitfalls. Since Biber supports Unicode people may want to define field names with non-ASCII characters (this doesn't work at the moment and I personally think it is a phenomenally bad idea, but half out of interest half because I think at some point people might ask for it: would it be possible to have Biber accept non-ASCII chars in the datamodel file [given a Unicode engine on the LaTeX side so we don't have to deal with the character representation of 8-bit LaTeX]?)
```latex
\RequirePackage{filecontents}
\begin{filecontents}{ufbibstyle.dbx}
\DeclareDatamodelEntrytypes{Uftype}
\DeclareDatamodelFields[type=field,datatype=literal]{uffielda,uffieldB,uffieldä}
\DeclareDatamodelEntryfields[Uftype]{uffielda,uffieldB,uffieldä}
\end{filecontents}
\begin{filecontents}{ufdbx.bib}
@Uftype{testdbx,
uffielda={A},
uffieldB={B},
tItLeaddoN = {something},
uffieldä = {ä},
}
@uftype{testdbxi,
uffieldA={A},
uffieldb={B},
tItLeaddoN = {something},
uffieldä = {ä},
}
\end{filecontents}
\documentclass{article}
\pagestyle{empty}
\usepackage[datamodel=ufbibstyle]{biblatex}
\DeclareBibliographyDriver{uftype}{% 
  \printfield{uffielda},\printfield{uffieldB},\printfield{uffieldä}}
\addbibresource{ufdbx.bib}
\begin{document}
\cite{testdbx,testdbxi}
\printbibliography
\end{document}
```
And then case-folding might be locale-dependent, which would potentially extremely confusing. (I'm thinking Turkish and its dotted and non-dotted is).

**Comment by plk** [comment]
I don't believe that Unicode case-folding is local-dependent - it's designed to get round this sort of thing and normalise to something which can e.g. be compared in tests. So, we could potentially accept anything in the `.dbx` (modulo a unicode TeX engine) and normalise to unicode case-folded form in the `.bbl`, documenting that drivers should always be written in case-folded form?

**Comment by moewew** [comment]
I don't know which case folding functions Perl and its Unicode modules provide, but in general there can be different expectations for different locales.

An English speaker would expect `i` (U+0069) to be the lowercase form of `I` (U+0049), but in Turkish they have the dotless and the dotted I and there `ı` (U+0131) is the lowercase of `I` (U+0049) and `i` (U+0069) the lowercase of `İ` (U+0130). This would be an issue for us since a Turkish user may well expect their custom Turkish field names to be normalised according to Turkish rules, but of course we expect the English field names to follow the English rules and it would break backwards compatibility if `article` and `ARTICLE` were not the same as soon as you add Turkish field names.... 

See also https://www.w3.org/International/wiki/Case_folding

**Comment by plk** [comment]
I meant really that we would have to normalise to something as the driver/style will be static and has to match the .bbl. So, we would have to say that everything should be in generic locale-free folded form in the .bbl and styles.

**Comment by moewew** [comment]
Yes, fixing a reference locale would make sense (as long as the reference locale does the right case folding for US-ASCII because we need that for backwards compatibility).

The question is whether Biber should write the `.bbl`  with normalised (lowercase for backwards compatibility) field names or with the field names exactly as they were in the data model/`.bcf`. I guess my preference would be the latter (output the `.bbl` in the same format as the declarations in the `.bcf`), because that would be the most consistent experience for users. But I don't know how `btparse` and Biber handle field names, so if that is too complex to pull of normalising in the `.bbl` and documenting that would be OK with me as well.

**Comment by plk** [comment]
It should be possible as `biber` has access to the real case in the `.bcf` - `btparse` only deals with input from the `.bib` and so I can probably write to the `.bbl` correctly and this is always written in the encoding/locale requested by the user anyway. So, internally `biber` could compare with, say, POSIX `C` locale, casefolded but write whatever is in the `datamodel`, in the encoding/locale of the `.bbl`, which is chosen by the user anyway.

**Comment by moewew** [comment]
That sounds good. Let's wait till after 2.13 is released (I guess only the FreeBSD builds are missing?) and then play with that a bit.

**Comment by u-fischer** [comment]
But as a short time measure please add to the documentation that the model should use lowercase letters.

**Comment by josephwright** [comment]
Case _folding_ is not locale dependent: it's specifically for 'machine' data not for 'text'. (There is the question of handling I/i and Turkic languages: one has to make a choice there.)

**Comment by plk** [comment]
Right - I intend to casefold all datamodel entrytype and field names for internal comparison for this reason and then output to the .bbl in the original case specified in the datamodel. By the way, perl 5.30, which will be required for the next `biber` release, implements Unicode 12.1 and also complete and automatic Turkish case folding, which is rather nice.

**Comment by plk** [comment]
This turns out to reveal some assumptions in `biber` which should be relaxed, specifically around encoding of fields. There is a first pass at generalising all of this on 2.14 DEV now. This allows full UTF-8 for entrytypes and fields. The `.bbl` output will use whatever casing was in the datamodel but the case in the `.bib` doesn't matter, as per usual `bibtex`.

Consider:

```
\RequirePackage{filecontents}
\begin{filecontents}{ufbibstyle.dbx}
\DeclareDatamodelEntrytypes{Uftype,Üftype}
\DeclareDatamodelFields[type=field,datatype=literal]{uffielda,uffieldB,uffieldä,uffieldÖ}
\DeclareDatamodelEntryfields[Uftype]{uffielda,uffieldB,uffieldä,uffieldÖ}
\DeclareDatamodelEntryfields[Üftype]{uffielda,uffieldB,uffieldä,uffieldÖ}
\end{filecontents}
\begin{filecontents}{ufdbx.bib}
@Uftype{test1,
  uffielda   = {uppertype uffielda},
  uffieldB   = {uppertype uffieldB},
  tItLeaddoN = {uppertype tItLeaddoN},
  uffieldä   = {uppertype uffieldä},
  uffieldö   = {uppertype uffieldÖ}
}

@üftype{test2,
  uffielda   = {upperatype uffielda},
  uffieldB   = {upperatype uffieldB},
  tItLeaddoN = {upperatype tItLeaddoN},
  uffieldä   = {upperatype uffieldä},
  uffieldÖ   = {uppertype uffieldÖ}
}
\end{filecontents}
\documentclass{article}
\pagestyle{empty}
\usepackage[datamodel=ufbibstyle]{biblatex}
\DeclareBibliographyDriver{Uftype}{% 
  \printtext{Uftype},\printfield{uffielda},\printfield{uffieldB},\printfield{uffieldä},\printfield{uffieldÖ}}
\DeclareBibliographyDriver{Üftype}{% 
  \printtext{Üftype},\printfield{uffielda},\printfield{uffieldB},\printfield{uffieldä},\printfield{uffieldÖ}}
\addbibresource{ufdbx.bib}
\begin{document}
\cite{test1,test2}
\printbibliography
\end{document}
```

The output is:

<img width="539" alt="Screenshot 2019-08-25 at 7 30 pm" src="https://user-images.githubusercontent.com/1220851/63653592-2f472600-c76f-11e9-8c26-66e4ffcea119.png">

**Comment by moewew** [comment]
Pushed a few words about this to `biblatex`'s `dev` docs: https://github.com/plk/biblatex/commit/90fb984847a401bf78a3f22e400482a3ac4e8014.

We're going to release 3.13a with a bug fix for https://github.com/plk/biblatex/issues/917 shortly. So if you (@u-fischer, @dcpurton) have something else that needs urgent attention, please let me know.

**Comment by plk** [comment]
Are we satisfied with the state of this now?

**Comment by moewew** [comment]
With https://github.com/plk/biber/issues/299 fixed I think everything is good here.
