### ISSUE TITLE
.bcf file not UTF-8 or even latin1: why not just overriden?

### ISSUE THREAD

**Issue by dbitouze** [plk/biber#291]
In some circumstances, one has to face with an error as the following one:
```
$ biber test
INFO - This is Biber 2.13
INFO - Logfile is 'test.blg'
ERROR - test.bcf is not UTF-8 or even latin1, how horrible.
INFO - ERRORS: 1
```
If I'm right, one just has to remove the `.bcf` and to rerun `biber` so it would be nice:
- for `biber` to run silently and overwrite this file,
- if not possible, at least for the message to suggest some actions to take.

**Comment by moewew** [comment]
**PLK** will need to comment on the important bits of this request, so I would just like to point out that you need to remove the `.bcf`, **rerun LaTeX** (or your favourite LaTeX flavour) and then rerun Biber.

The `.bcf` file is written by LaTeX *for* Biber. If it is corrupted Biber can't know what to do. Simply removing the file is not enough for Biber to figure out what to do, the file needs to be regenerated and must be well formed.

In particular Biber can not continue to run (silently or otherwise) meaningfully with a corrupted `.bcf`. And Biber can also not (meaningfully) overwrite the `.bcf` file since it doesn't know what to put in there in the first place (the contents of the file must come from LaTeX/the `biblatex` side).

So I guess only the second part of the request can be reasonably fulfilled.

**Comment by dbitouze** [comment]
>you need to remove the `.bcf`, rerun LaTeX (or your favourite LaTeX flavour) and then rerun Biber.

Of course, you're right.

>So I guess only the second part of the request can be reasonably fulfilled.

OK, thanks.

**Comment by plk** [comment]
I have made a more informative error message in 2.14 DEV:

"... is not UTF-8 or even latin1, please delete it and run biblatex again or check that biblatex is writing a valid .bcf file."

**Comment by dbitouze** [comment]
>run biblatex again or check that biblatex

Should be: "run latex again or check that latex", isn't it?

**Comment by plk** [comment]
Right, fixed.
