### ISSUE TITLE
Can't locate Biber.pm in @INC

### ISSUE THREAD

**Issue by a2975667** [plk/biber#313]
I installed biber visa apt-get on Ubuntu 18.04.
When I try to verify the installation using biber --version, the following error pops up.
`Can't locate Biber.pm in @INC (you may need to install the Biber module) (@INC contains: /home/linuxbrew/.linuxbrew/Cellar/perl/5.30.1/lib/perl5/site_perl/5.30.1/x86_64-linux-thread-multi /home/linuxbrew/.linuxbrew/Cellar/perl/5.30.1/lib/perl5/site_perl/5.30.1 /home/linuxbrew/.linuxbrew/Cellar/perl/5.30.1/lib/perl5/5.30.1/x86_64-linux-thread-multi /home/linuxbrew/.linuxbrew/Cellar/perl/5.30.1/lib/perl5/5.30.1 /home/linuxbrew/.linuxbrew/lib/perl5/site_perl/5.30.1) at /usr/bin/biber line 17.
BEGIN failed--compilation aborted at /usr/bin/biber line 17.`

Not sure if this is related to #214.
I am trying to use biblatex on WSL

**Comment by moewew** [comment]
Most people don't install Biber from source. I would expect that `apt install biber` would install a working Biber on Ubuntu.

The Biber binaries distributed on CTAN and included in MikTeX and TeX live need to unpack themselves into a cache before they can be used. Maybe something went wrong there. See if there is a cache you can delete https://tex.stackexchange.com/q/140814/35864.

But I seem to remember that the Debian Biber is in fact the Perl script and not a packed binary. In that case there won't be any cache. You may have to contact the Ubuntu/Debian Biber distributor.

**Comment by a2975667** [comment]
I resolved this issue myself.
So biblatex and bibtex need certain version to match together. 
So apt install biber might not match the biblatex version that comes with apt install texlive-full.
So the best way it seems is to install everything from texlive website that uses can modules directly.
(and remember to update the path!)

**Comment by moewew** [comment]
I won't disagree that it is a good idea to install a "vanilla" TeX live from TUG.org (https://tex.stackexchange.com/q/1092/35864). It is a route many people who like their TeX system more up-to-date take. But it's not for everybody.

Nevertheless, I would expect the Biber and `biblatex` versions served by `apt-get` to match. If that is not the case, contact the Ubuntu/Debian package maintainer. Shipping mismatched versions would be a serious error that should be resolved (It definitely has happened before https://tex.stackexchange.com/q/458775/35864, https://bugs.launchpad.net/ubuntu/+source/biber/+bug/1770516). I can not say conclusively whether your issue was due to a version mismatch. At the moment I would say the error message does *not* suggest a version mismatch. Usually the message for a version mismatch is much more explicit, e.g.
```
INFO - This is Biber 2.12
INFO - Logfile is file.blg
INFO - Reading 'file.bcf'
ERROR - Error: Found biblatex control file version 3.7, expected version 3.5.
        This means that your biber (2.12) and biblatex (3.14) versions are incompatible.
        See compat matrix in biblatex or biber PDF documentation.
INFO - ERRORS: 1
```

**Comment by a2975667** [comment]
Yes, that was the issue I got when I try to run biblatex with apt biber.
The original issue comes when I try to build it from source.
(And also when utilizing the biber + biblatex that comes with texlive-full when compiling)
