### ISSUE TITLE
Last name detected incorectly in inconsistent bibentries

### ISSUE THREAD

**Issue by RalfJung** [plk/biber#320]
I had a lot of trouble with biber/biblatex picking up the wrong string for the last name of some authors I am citing, and after many hours of debugging ended up "solving" the problem by switching from biber to bibtex as backend. Here's a reduced bibfile that demonstrates the problem:
```
@Article{pottier:jfp13,
  author = 	 {Fran\c{c}ois Pottier},
	title={Syntactic soundness proof of a type-and-capability system with hidden state},
	journal={{JFP}},
	volume={23},
	number={1},
	pages={38--144},
	year={2013},
  doi       = {10.1017/S0956796812000366},
}

@article{Mezzo,
  title={The design and formalization of {Mezzo}, a permission-based programming language},
  author={Balabonski, Thibaut and Pottier, Fran{\c{c}}ois and Protzenko, Jonathan},
  journal={TOPLAS},
  volume={38},
  number={4},
  year={2016},
  doi={10.1145/2837022}
}



@techreport{compcertmemory,
  title={The {Com\nolinebreak{}pCert} memory model, version 2},
  author={Leroy, Xavier and Appel, Andrew and Blazy, Sandrine and Stewart, Gordon},
  year={2012},
  institution={Inria},
  number={RR-7987},
  url = {https://hal.inria.fr/hal-00703441},
  type= {Technical Report},
}


@InProceedings{appel:fpcc,
  author = 	 {Andrew W. Appel},
  title = 	 {Foundational proof-carrying code},
  booktitle = {LICS},
  year = 	 {2001},
  doi       = {10.1109/LICS.2001.932501},
}

@article{compcert-aliasing,
  author    = {Xavier Leroy and
               Sandrine Blazy},
  title     = {Formal Verification of a {C}-like Memory Model and Its Uses for Verifying
               Program Transformations},
  journal   = {{JAR}},
  volume    = {41},
  number    = {1},
  pages     = {1--31},
  year      = {2008},
  doi       = {10.1007/s10817-008-9099-0},
}
```
The issue is that with the "authortitle" cite style, `Mezzo` ends up as

> Balabonski, François Pottier, and Protzenko, “The design and formalization of Mezzo, a permission-based programming language”

and `appel:fpcc` ends up as

> A. W. Appel, “Foundational proof-carrying code”

What I would expect (and what happens with bibtex) is that the first citation gets authors "Balabonski, Pottier, and Protzenko" and the second citation gets "Appel".

I understand that the data here is inconsistent, but given that bibtex can handle this inconsistent data fine without using entirely wrong last names, I think it is a bug in biber to do what it does -- and it basically makes biber unusable for me, I have a huge bibfile and don't want to have to worry that the tiniest inconsistency causes incorrect citations like this.

Removing any one of these bibentries fixes one of the two citations. In particular, somehow, removing `compcert-aliasing` fixes Appel's name even though he's not on that paper?!?

Cc @moewew this is the biber problem I mentioned on SO.

**Comment by moewew** [comment]
You can just set the option `uniquename=false`. See also https://tex.stackexchange.com/q/91225/35864, https://tex.stackexchange.com/q/134535/35864 on TeX.SX.

**Comment by RalfJung** [comment]
Oh, wow... so this is actually deliberate behavior? I feel like that's fairly suboptimal. The failure mode for messy data (and most real-world data is messy) is much worse than it used to be with bibtex. As a user, this feels like a regression to me.

But thanks for pointing out that option, at least for this document I might now be able to switch to biber again. For future documents, I am considering if old-style bibtex isn't working better for me, given how many problems I've had.

(It is exactly this kind of behavior why I said in another thread that I reflexively disable "LaTeX smartness" whenever I see it. ;)

**Comment by RalfJung** [comment]
For "Pottier", it didn't just add initials, it added the full first name. Given the feature description, shouldn't it have done "F. Pottier" instead? Or did it decide to be even smarter and expand the name further when the initials are the same but it sees a difference elsewhere in the name?

**Comment by RalfJung** [comment]
But how does this explain that removing the `compcert-aliasing` citation affects how Appel's name is printed?

**Comment by moewew** [comment]
OK, let's unpack what's going on here with a few fully working example documents.

First Pottier.
```latex
\documentclass[british]{article}
\usepackage[T1]{fontenc}
\usepackage[utf8]{inputenc}
\usepackage{babel}
\usepackage{csquotes}

\usepackage[style=authoryear, backend=biber]{biblatex}

\begin{filecontents}{\jobname.bib}
@Article{pottier:jfp13,
  author = 	 {Fran\c{c}ois Pottier},
	title={Syntactic soundness proof of a type-and-capability system with hidden state},
	journal={{JFP}},
	volume={23},
	number={1},
	pages={38--144},
	year={2013},
  doi       = {10.1017/S0956796812000366},
}
@article{Mezzo,
  title={The design and formalization of {Mezzo}, a permission-based programming language},
  author={Balabonski, Thibaut and Pottier, Fran{\c{c}}ois and Protzenko, Jonathan},
  journal={TOPLAS},
  volume={38},
  number={4},
  year={2016},
  doi={10.1145/2837022}
}
\end{filecontents}
\addbibresource{\jobname.bib}

\begin{document}
\autocite{pottier:jfp13}

\autocite{Mezzo}

\printbibliography
\end{document}
```
reproduces the behaviour you are complaining about
> ![(François Pottier 2013)//(Balabonski, François Pottier and Protzenko 2016)](https://user-images.githubusercontent.com/6755835/84161076-2cec5900-aa6f-11ea-8e66-c1c0e9470cb8.png)

That is due to the `uniquename` feature.

By default the `uniquename` feature is turned on and tries to make names in the citations unambiguous by adding given name initials (if that is enough) or the full given name (if initials aren' enough). Since `Fran\c{c}ois Pottier` and `Pottier, Fran{\c{c}}ois` appear as two different names with same same given name initials to Biber, namely
```
        {{un=2,uniquepart=given,hash=0f01c7f7d5be720471b86a3d309410d6}{%
           family={Pottier},
           familyi={P\bibinitperiod},
           given={Fran{ç}ois},
           giveni={F\bibinitperiod},
           givenun=2}}%
```
and
```
        {{un=2,uniquepart=given,hash=0f01c7f7d5be720471b86a3d309410d6}{%
           family={Pottier},
           familyi={P\bibinitperiod},
           given={François},
           giveni={F\bibinitperiod},
           givenun=2}}%
      }
```
Biber will force the full name "François Pottier".
Note that the only difference is the pair of braces around the 'ç', which you can't see in the output, but Biber sees it. "F. Pottier" for both would still be ambiguous, but "Fran{ç}ois Pottier" and "François Pottier" are different (for Biber).
(Whether you input the name in `<Given> <Family>` or `<Family>, <Given>` order does *not* matter.)

Biber simply doesn't know that these two names refer to the same person. A similar case occurs 
when people use different forms of their name, e.g. Donald Knuth and Donald E. Knuth or in the Appel case.

An example what the feature is supposed to do can be found in the `biblatex` documentation

Assume you have the following works
> John Doe 2008
> Edward Doe 2008
> John Smith 2008
> Jane Smith 2008

then with `uniquename` off you'll just get
> Doe 2008a
> Doe 2008b
> Smith 2008a
> Smith 2008b

but with `uniquename=true`, you'll get
> J. Doe 2008
> E. Doe 2008
> John Smith 2008
> Jane Smith 2008

with just enough info to make the names unique.

This is the ideal scenario, obviously, if the same person published under slightly different versions of the same name or journals/your `.bib` entries are inconsistent between using given name initials or full given names, then this may not always give the best results.


I should point out that technically speaking `Fran\c{c}ois Pottier` is the wrong input, LaTeX-macro-escapes for non-ASCII-chars should be protected with a pair of braces in the BibTeX input (contrary to what you'd do in the body of your TeX document). This wouldn't solve the underlying issue here though, as you could also give the name as `François Pottier` using UTF-8 directly, in which case there wouldn't be a pair of braces again. This will get better in the next version of Biber, where braces that just mark up LaTeX-macro-escapes for non-ASCII chars will be removed https://github.com/plk/biber/issues/316. But that does not change the fact that "Donald Knuth", "D. Knuth", "D. E. Knuth" and "Donald E. Knuth" will be treated as different people.

Anyway, with `unquename=false` you get the output you want
```latex
\documentclass[british]{article}
\usepackage[T1]{fontenc}
\usepackage[utf8]{inputenc}
\usepackage{babel}
\usepackage{csquotes}

\usepackage[style=authoryear, backend=biber, uniquename=false]{biblatex}

\begin{filecontents}{\jobname.bib}
@Article{pottier:jfp13,
  author = 	 {Fran\c{c}ois Pottier},
	title={Syntactic soundness proof of a type-and-capability system with hidden state},
	journal={{JFP}},
	volume={23},
	number={1},
	pages={38--144},
	year={2013},
  doi       = {10.1017/S0956796812000366},
}
@article{Mezzo,
  title={The design and formalization of {Mezzo}, a permission-based programming language},
  author={Balabonski, Thibaut and Pottier, Fran{\c{c}}ois and Protzenko, Jonathan},
  journal={TOPLAS},
  volume={38},
  number={4},
  year={2016},
  doi={10.1145/2837022}
}
\end{filecontents}
\addbibresource{\jobname.bib}

\begin{document}
\autocite{pottier:jfp13}

\autocite{Mezzo}

\printbibliography
\end{document}
``` 
> ![Pottier 2013)//(Balabonski, Pottier and Protzenko 2016) ](https://user-images.githubusercontent.com/6755835/84162421-a769a880-aa70-11ea-9fb4-022527b74198.png)


---

The Appel issue is also caused by `uniquename`, but the issue only shows when `compcert-aliasing` is involved due to `uniquelist`.

```latex
\documentclass[british]{article}
\usepackage[T1]{fontenc}
\usepackage[utf8]{inputenc}
\usepackage{babel}
\usepackage{csquotes}

\usepackage[style=authoryear, backend=biber]{biblatex}

\begin{filecontents}{\jobname.bib}
@techreport{compcertmemory,
  title={The {Com\nolinebreak{}pCert} memory model, version 2},
  author={Leroy, Xavier and Appel, Andrew and Blazy, Sandrine and Stewart, Gordon},
  year={2012},
  institution={Inria},
  number={RR-7987},
  url = {https://hal.inria.fr/hal-00703441},
  type= {Technical Report},
}
@InProceedings{appel:fpcc,
  author = 	 {Andrew W. Appel},
  title = 	 {Foundational proof-carrying code},
  booktitle = {LICS},
  year = 	 {2001},
  doi       = {10.1109/LICS.2001.932501},
}
@article{compcert-aliasing,
  author    = {Xavier Leroy and
               Sandrine Blazy},
  title     = {Formal Verification of a {C}-like Memory Model and Its Uses for Verifying
               Program Transformations},
  journal   = {{JAR}},
  volume    = {41},
  number    = {1},
  pages     = {1--31},
  year      = {2008},
  doi       = {10.1007/s10817-008-9099-0},
}
\end{filecontents}
\addbibresource{\jobname.bib}

\begin{document}
\section{With \texttt{compcert-aliasing}}
\autocite{compcertmemory}

\autocite{appel:fpcc}

\autocite{compcert-aliasing}

\newrefsection
\section{Without \texttt{compcert-aliasing}}

\autocite{compcertmemory}

\autocite{appel:fpcc}

\newrefsection
\section{\texttt{compcert-aliasing} on its own}

\autocite{compcert-aliasing}
\end{document}

```
> ![(Leroy, A. Appel et al. 2012) (A. W. Appel 2001) (Leroy and Blazy 2008)//(Leroy et al. 2012) (Appel 2001)//(Leroy and Blazy 2008)](https://user-images.githubusercontent.com/6755835/84164387-c10bef80-aa72-11ea-992b-f996699a2836.png)

Note that not only does Appel get initials only in the first case, the name isn't even shown for `compcertmemory` if `compcert-aliasing` isn't cited.

That is because `uniquelist` tries to make the abbreviated name lists in citations unique (so that two lists with different names don't both get abbreviated to "Smith et al."). Now Biber thinks that putting together "Leroy and Blazy 2008" and "Leroy et al. 2012" would be ambiguous and expands the name list of the latter to "Leroy, Appel et al. 2012" (there can be no ambiguity here, since the first two authors differ in both cases).

Names are only disambiguated by `uniquename` if they are actually shown in the citations. Since "Leroy et al. 2012" is expanded to "Leroy, Appel et al. 2012", there are now two Appels and you get disambiguation.

Again, this behaviour can be stopped by using `uniquename=false,` but here `uniquelist=false,` would also help.

```latex
\documentclass[british]{article}
\usepackage[T1]{fontenc}
\usepackage[utf8]{inputenc}
\usepackage{babel}
\usepackage{csquotes}

\usepackage[style=authoryear, backend=biber, uniquelist=false]{biblatex}

\begin{filecontents}{\jobname.bib}
@techreport{compcertmemory,
  title={The {Com\nolinebreak{}pCert} memory model, version 2},
  author={Leroy, Xavier and Appel, Andrew and Blazy, Sandrine and Stewart, Gordon},
  year={2012},
  institution={Inria},
  number={RR-7987},
  url = {https://hal.inria.fr/hal-00703441},
  type= {Technical Report},
}
@InProceedings{appel:fpcc,
  author = 	 {Andrew W. Appel},
  title = 	 {Foundational proof-carrying code},
  booktitle = {LICS},
  year = 	 {2001},
  doi       = {10.1109/LICS.2001.932501},
}
@article{compcert-aliasing,
  author    = {Xavier Leroy and
               Sandrine Blazy},
  title     = {Formal Verification of a {C}-like Memory Model and Its Uses for Verifying
               Program Transformations},
  journal   = {{JAR}},
  volume    = {41},
  number    = {1},
  pages     = {1--31},
  year      = {2008},
  doi       = {10.1007/s10817-008-9099-0},
}
\end{filecontents}
\addbibresource{\jobname.bib}

\begin{document}
\section{With \texttt{compcert-aliasing}}
\autocite{compcertmemory}

\autocite{appel:fpcc}

\autocite{compcert-aliasing}

\newrefsection
\section{Without \texttt{compcert-aliasing}}

\autocite{compcertmemory}

\autocite{appel:fpcc}

\newrefsection
\section{\texttt{compcert-aliasing} on its own}

\autocite{compcert-aliasing}
\end{document}
```
>  ![(Leroy et al. 2012) (Appel 2001) (Leroy and Blazy 2008)](https://user-images.githubusercontent.com/6755835/84165716-4ba11e80-aa74-11ea-9b22-adab145a4ad3.png)

**Comment by RalfJung** [comment]
@moewew thanks for the detailed explanation!

> Note that not only does Appel get initials only in the first case, the name isn't even shown for compcertmemory if compcert-aliasing isn't cited.

Ah, that solves the mystery of the third bibentry having an effect. Not knowing about these "global uniqueness" efforts of biblatex/biber, this looked very much like a "spooky action at a distance" to me, where changes to one entry magically affected other entries. At least that is explained now. :)

Given that the authortitle style cites the full title of the paper, I'd rather have ambiguous author lists than inconsistent citing -- even if two papers are both by "Jung et al", the reader can immediately tell them apart by their title, whereas several proofreaders remarked to me that they were startled by there being different citation styles for different people/papers (sometimes with and sometimes without initials; different number of authors before "et al"). Together with the fact that the docs say the default for the `unique*` options is `false` (and the remark about styles changing that is quite far removed in the docs), this came quite unexpected.
