### ISSUE TITLE
Biber 2.15 handles `{-}` in names incorrectly

### ISSUE THREAD

**Issue by lorenzhs** [plk/biber#329]
I use biber through the debian package, and 2.15 landed in Debian unstable a few days ago. My bibliography file contains several entries where dashes in names of the author are escaped: `author={Hans{-}Peter Geerdes}`. This worked fine with biber 2.14 but produces a bbl file with too many closing `}` with biber 2.15:

```bibtex
@misc{geerdes1998fish,
  author = {Hans{-}Peter Geerdes and others},
  title = {How much is the fish?},
  year = 1998
}
```

```latex
    \entry{geerdes1998fish}{misc}{}
      \true{moreauthor}
      \true{morelabelname}
      \name{author}{1}{}{%
        {{hash=fb1a47834c2a69da853e28fd2db2b299}{%
           family={Geerdes},
           familyi={G\bibinitperiod},
           given={Hans{-}Peter},
           giveni={H\bibinithyphendelim }\bibinitperiod}}}%
      }
      \strng{namehash}{b8530f63a23c20acbfc51e7e7fbc5399}
      \strng{fullhash}{b8530f63a23c20acbfc51e7e7fbc5399}
      \strng{bibnamehash}{b8530f63a23c20acbfc51e7e7fbc5399}
      \strng{authorbibnamehash}{b8530f63a23c20acbfc51e7e7fbc5399}
      \strng{authornamehash}{b8530f63a23c20acbfc51e7e7fbc5399}
      \strng{authorfullhash}{b8530f63a23c20acbfc51e7e7fbc5399}
      \field{labelalpha}{Gee+98}
      \field{sortinit}{G}
      \field{sortinithash}{62eb2aa29549e4fdbd3cb154ec5711cb}
      \field{labelnamesource}{author}
      \field{labeltitlesource}{title}
      \field{title}{How much is the fish?}
      \field{year}{1998}
    \endentry
```

The `}` after `\bibinithyphendelim` should not be there.

**Comment by plk** [comment]
Is there a reason for such an odd protection of a hyphen here? It's very hard with initials generation to cope with every possible strange edge case ...

**Comment by moewew** [comment]
Curly braces can be a bit of a pain, because they have so many different 'escape' meanings in BibTeX. Some of them are undesirable for Biber and are cleaned up automatically (for example `{\"a}` should become `ä` not `{ä}`), but others need to be preserved. As it turns out this is a huge mess, especially if you do that with RegExps, which as I understand don't really do nesting of braces as naturally as in TeX. My advice therefore is to try to use a few curly braces as possible.

If you want to force a particular initial, you may want to consider using the extended name format, cf. https://tex.stackexchange.com/q/559116/35864.

---

@plk If I understand the fix https://github.com/plk/biber/commit/fa312ce402fe581ba7cc0890c83a1d47c2610e26 correctly, it treats `{-}` just like `-` and just splits `Hans{-}Peter` into `Hans`/dash/`Peter`. The BibTeX behaviour seems to do the opposite (i.e. simply treat `{-}` as a normal character and don't split on it, so that we get `Hans{-}Peter` as a  single unit). So this might not give the result @lorenzhs hoped for.

```latex
\documentclass[british]{article}
\usepackage[T1]{fontenc}
\usepackage[utf8]{inputenc}
\usepackage{babel}
\usepackage{csquotes}


\begin{filecontents}[force]{\jobname.bib}
@misc{geerdes1998fish,
  author = {Hans-Peter Geerdes and others},
  title = {How much is the fish?},
  year = 1998
}
\end{filecontents}


\begin{document}
\cite{geerdes1998fish}
\bibliographystyle{abbrv}
\bibliography{\jobname}
\end{document}
```

I'm not too fussed either way, but if the change to make Biber behave more like BibTeX is a s simple as https://github.com/plk/biber/commit/fa312ce402fe581ba7cc0890c83a1d47c2610e26 then it may be easier for end users if we stick to emulating BibTeX better.

**Comment by plk** [comment]
Ah, I didn't look at the `.bbl` long enough - I see the point of this now, that is indeed an abstruse way of forcing it not to split ...

**Comment by lorenzhs** [comment]
> Is there a reason for such an odd protection of a hyphen here? It's very hard with initials generation to cope with every possible strange edge case ...

The entries of my bibliography file that were affected by this were copied from [dblp](https://dblp.org/), I don't know why they do this but I had >10 occurrences of it.

Therefore, personally, I don't care about the protection of the dashes, so in my view, normalization to `Hans-Peter` is perfectly reasonable. But I guess others might see it differently.

**Comment by plk** [comment]
2.16 DEV should now handle this like BibTeX does.

**Comment by lorenzhs** [comment]
Thanks a lot! Shall I close this?

**Comment by junwei-wang** [comment]
I had the same issue in https://github.com/plk/biber/issues/336 .
