### ISSUE TITLE
Biber musl executable for biber 2.11

### ISSUE THREAD

**Issue by WtfJoke** [plk/biber#335]
Hi there

I would like to create an alpine docker image where [tectonic](https://tectonic-typesetting.github.io) is bundled with biber.
Since tectonic uses latex-2018 (which uses biblatex 3.4) distro biber 2.11 is the latest compatible version. 
I saw that you provided biber executables for linux musl starting at version 2.13 (see https://github.com/plk/biber/issues/255). Can you provide them also for 2.11?

Thank you very much in advance.

**Comment by plk** [comment]
Unfortunately, I don't build the MUSL binaries but I'm mentioning  the MUSL builder here (@krumeich) so he can respond.

**Comment by krumeich** [comment]
Hi!

It seems that my build chain doesn't offer enough backwards compatibility for producing v2.11. Dozens of tests are failing.

Since you seem to be familiar with Docker, I invite you to try building biber v2.11 yourself. The build process is designed as a Docker container. You can find the sources for the image at [krumeich/biber-alpine](https://github.com/krumeich/biber-alpine). There's a README that explains how to call Docker (or use the Makefile). My approach would be to pass the necessary environment variable that tells Perl not to run any tests, probably by skipping the `./Build test` step in `biberbuild.sh`. 

Anyway, there might be other things to consider: 

* The version of Perl that biber requires. Current build of biber require Perl 5.30.0. As far as I remember, biber 2.13 required Perl 5.26.0 I'm not sure if there is a backwards compatibility issue at hand.
* Every target system requires its own configuration directory in the biber source tree. I added the `Linux_x86_64-musl` directory, but not until sometime in version 2.13. You would have to fork the biber sources, create a branch from the v2.11 tag and cherry pick the four commits that led up to pull request #282 . 

Hope this helps!

**Comment by krumeich** [comment]
Small addendum: The errors look very much like the errors that Perl produced during my very first trial runs 18 months ago (see https://github.com/plk/biber/issues/255#issuecomment-468958100). @moewew suggested back then that this might be due to version changes in the Unicode::collate. This is why I decided not to provide a binary for the then-current v2.12 but instead wait for v2.13. 

Anyway, all this to say that going back to v2.11 is far from trivial. :-|

**Comment by WtfJoke** [comment]
Thanks a lot for your super fast responses, thats awesome! I appreciate that a lot (including the detailed answer).


> Since you seem to be familiar with Docker, I invite you to try building biber v2.11 yourself. The build process is designed as a Docker container.

I certainly could try that, allthough im familiar with Docker im havent done anything with Pearl yet 😄 


> My approach would be to prevent Perl from running any tests, probably by skipping the `./Build test` step in `biberbuild.sh`.

> version changes in the Unicode::collate. This is why I decided not to provide a binary for the then-current v2.12 but instead wait for v2.13.

I'm not quite sure. Without tests I probably just have a non working binary (even though it would be a start). 
And I cant really grasp whats its all about Unicode::collate. Probably because im not into the topic. 

Out of curiosity, because I dont understand how building the v2.12 lead to these errors. Have you started your work of the main branch and these issues were related to that it progressed further (eg. between v2.12 and v2.13)?

>     * Every target system requires its own configuration directory in the biber source tree. I added the `Linux_x86_64-musl` directory, but not until sometime in version 2.13. You would have to fork the biber sources, create a branch from the v2.11 tag and cherry pick the four commits that led up to pull request #282 .

Thats a good hint.  I probably would have started exactly like this, checkout v2.11 and try to build it using your instructions. I am not sure how the Unicode:collate issue will be a problem if I would try it like that. But Its probably hard to figure out how to build v2.11 when having never build any pearl software 🙈 



> Anyway, all this to say that going back to v2.11 is far from trivial. :-|

Yes it sounds like that, so I guess its probably not worth the effort. 😥  And as already stated I have no experience in Pearl. So it probably doesnt make sense a lot to progress this further 
(I currently try your build instructions and atm its building  *_small yay_* 😛 ).

I'm unsure if we should keep the issue open or just close it.

**Comment by krumeich** [comment]
You're most welcome. Honestly, I feel your pain. When I approached @plk about providing a MUSL build of biber, I was in a very similar situation: I knew a bit about Docker and hardly anything about Perl. Since then, I haven't written a single line of Perl, so not much progress there. The build chain that is implemented in [krumeich/biber-alpine](https://github.com/krumeich/biber-alpine) feels more like a giant set of Lego. :-)))

So, I can't really help you with the intricacies of Unicode::Collate (or any other Perl library, for that matter). 

As for your question about v2.12/v2.13: v2.12 had been released prior. If I recall correctly, I started off biber's `dev` branch around commit 6b358171c60771125adc981d9fe48a1fddb6abb9. By then, the changes in v2.13 had been made to accommodate a newer release of Unicode::Collate. 

When I established that I could biber v.213-dev successfully, I went back to try the then-released version v2.12. This didn't work at first, but eventually I got a version working that I put on my own website. Most unfortunately, I can't really remember what I to overcome/ignore the problem with failed tests.

If you want to give it another try, let's leave the issue open for another couple days, provided @plk doesn't mind. Otherwise, feel free to close it. Good luck.

**Comment by WtfJoke** [comment]
After your kind words I wanted to give it a try.

It looked like im on a good path (I used your image with another base image scottw/alpine-perl:5.26.0). 
The same tests are failing (at least the same diff) as you had in https://github.com/plk/biber/issues/255#issuecomment-468958100. 

For example [lasttestlog.txt](https://github.com/plk/biber/files/5215268/lasttestlog.txt)

Is there some way to find out which version of Unicode:Collate is installed and which one is needed for the build/tests of biber 2.11?

I also ran `biber --validate-control test-dev.bcf`

Sadly it failed:
```
biber --validate-control test-dev.bcf
INFO - This is Biber 2.11
INFO - Logfile is 'test-dev.blg'
ERROR - 'test-dev.bcf' failed to validate against schema '/usr/local/lib/perl5/site_perl/5.26.0/Biber/bcf.rng'
INFO - ERRORS: 1
```

Any tipps/hints? 😄

**Comment by krumeich** [comment]
Awesome! Congratulations. This looks very promising indeed. 

The test-dev file is always tailored towards a specific version of biblatex. So I suggest that you once again go back in history. I don't know if @plk still has the old test files, that were used vor v2.11. You might want to try krumeich/biber-alpine commit bca2391ac23e010702abdeb4811583c981b04af5 which is when I first added the  test files to my repo. These are the oldest files I can get a hold of.

**Comment by WtfJoke** [comment]
Just a quick headsup.
I tested my alpine biber binary against an existing .bcf file of mine which I know works with 2.11.
And it seemed to work (at least I cant spot any errors 😄 ) 🎉 

See [biberlog.txt](https://github.com/plk/biber/files/5228297/biberlog.txt)

Havent tested an old test file of your repo, though. 
Would still be great if we would find a solution for the failing tests.

**Comment by krumeich** [comment]
This is excellent news! In your position, I'd be happy now and leave things as they are. Don't mind the failing tests during the build. If the `.bcf` file works and biber doesn't crash, that is as good an acceptance test as you can expect. 

Good job! If you don't mind, I'd close the issue now.

**Comment by WtfJoke** [comment]
Hey @krumeich 

Thanks! However I opened this bug with the goal to have the binary publicly available in an official place (for example sourceforge) to download. 

Until that is the case I would leave this bug open. 😅 

The question is what should be done in order to upload it. 
- PR against biber for v2.11 build script for linux musl (available here: https://github.com/WtfJoke/biber/blob/v2.11_musl/dist/linux_x86_64-musl/build.sh) - How do you handle contributions to an old version?
- PR against biber-alpine for the slightly modified Dockerfile.build (just a different base image).
- ... anything I haven't thought of.

**Comment by krumeich** [comment]
Hey, sorry to keep you waiting. I can think of two ways to go forward from this point: 

- Either you add your changes to the plk/biber repo. That would probably result in a dangling branch off of the v2.11 tag (or whereever your branch starts). Dangling because merging these commits would be too much hassle. I would then create the v2.11-musl build and put it on SF
- Or you find a way to send me your binary. I would then put that build on SourceForge. This is probably the easier solution.

What do you think?

**Comment by WtfJoke** [comment]
No worries, I am happy that you have responded 😄 

>     * Either you add your changes to the plk/biber repo. That would probably result in a dangling branch off of the v2.11 tag (or whereever your branch starts). Dangling because merging these commits would be too much hassle. I would then create the v2.11-musl build and put it on SF

Yes, this would be possible. It probably would be just 1 commit (with the script as it is in my fork). But then it would need first a branch (for merging the PR) and recreating the tag (after PR is merged). Probably this depends how @plk would want to integrate that.


>     * Or you find a way to send me your binary. I would then put that build on SourceForge. This is probably the easier solution.

Here would be the binary: [biber.zip](https://github.com/plk/biber/files/5255582/biber.zip) and my test files as a reference (and for you to test it): [testfiles.zip](https://github.com/plk/biber/files/5255621/testfiles.zip)

**Comment by krumeich** [comment]
Done. Your build is now up on SF in a fresh "Linux-musl" directory for version 2.11:

https://sourceforge.net/projects/biblatex-biber/files/biblatex-biber/2.11/binaries/Linux-musl/

I'd abstain from creating a pull request and merging this commit. You can't merge it into master or dev, because the changes you made already exist there (or did I get something wrong about git?). Please confirm that this is appropriate for working with tectonic. Then we should close the issue.

**Comment by WtfJoke** [comment]
Hey Alexander, thanks a lot for uploading it 🙏 

Tested it with tectonic and it worked (just tested my "old" thesis) 🎉 

I wont open a PR then. The changes I made doesnt exist there (on dev/master and shouldnt, but could on v2.11), there are slight differences in the one from the current dev and the one I used for creating the binary for 2.11 (mostly just perl and dep versions, other path to unicode:collate etc..).

See here for full diff:
https://www.diffnow.com/report/8brat

Sidenote: Probably it would make sense to use `${perlv}` in a few more places on dev, too.

Anyways, thanks a lot for your support. I'll close the issue now 😄 
Cheers
Manuel
