### ISSUE TITLE
Update biber versions

### ISSUE THREAD

**Issue by ReneTC** [plk/biber#347]
How to update the biber version?
When I run "biber latexfile.tex" I get:

`ERROR - Error: Found biblatex control file version 3.7, expected version 3.5.
This means that your biber (2.12) and biblatex (3.14) versions are incompatible.
See compat matrix in biblatex or biber PDF documentation.
INFO - ERRORS: 1
`

**Comment by moewew** [comment]
The correct/best™ way to update Biber will depend on how you installed Biber or rather your whole TeX system.

On a MikTeX system you should just fire up the MikTeX Console and update your system (update all packages). Remember to update both in Admin *and* User mode if you have a multi-user MikTeX installation.

If you have a TeX Live system the correct way depends on whether you installed the system from TUG.org directly ('vanilla TeX Live') or if you got it from your Linux distribution (e.g. via `apt-get` and friends). A TeX Live installed via your Linux distribution's package sources can only be updated via your Linux distribution (i.e. via `apt-get`), but generally these TeX Live packages are frozen and not upgradeable (this is the case for Ubuntu for example). If you got your TeX Live from TUG.org, you can run  `tlmgr` to update your system. Note that only TeX Live 2020 currently receives updates via `tlmgr`. Older versions are frozen and cannot be updated any longer.

Some more details can be found on TeX.SX: https://tex.stackexchange.com/q/55437/35864 (and specifically for MikTeX https://tex.stackexchange.com/q/108447/35864).

**Comment by ReneTC** [comment]
Thank you @moewew ! I think I misunderstood since an anaconda package linked to this repo. This one:
https://anaconda.org/malramsay/biber

Do you know if I can update it? It only comes with version 2.12-0

**Comment by moewew** [comment]
Mhhh, I didn't know you could get Biber from Anaconda. The crucial question now is where the rest of your TeX system comes from (that is to say how you installed the TeX executables and TeX packages). Did you also get it from Anaconda? If so, you should make sure all packages are fully up to date (no idea how that works with Anaconda, I'm afraid) and if there are still package mismatches you probably need to contact the people who package and distribute Biber (and the rest of TeX) for Anaconda, since they should package matching versions.

Usually, the only sound way to avoid mayhem is to install Biber via your TeX system or from the same source as your TeX system to make sure that the versions of `biblatex` (from the TeX system) and Biber match. If you get them from different sources or install via unsupported side channels or manually you are usually on your own, because there is no guarantee that the different sources all update `biblatex` and Biber at the same time to matching versions.

**Comment by ReneTC** [comment]
thank you very much for the input @moewew  I've followed your advice to find a biber via TeX system and everythning runs perfectly know. Appreciate your help!
