### ISSUE TITLE
No output in tool mode

### ISSUE THREAD

**Issue by jonsterling** [plk/biber#350]
I am very suddenly having a bizarre problem, but I don't know what is causing it, I hope you can help me. If I run a command like

    biber --tool --output-encoding=ascii --output-file=out.bib refs.bib            

it used to generate a file called `out.bib`. What happens now is that I see the following output:

```
INFO - This is Biber 2.15 running in TOOL mode
INFO - Logfile is 'refs.bib.blg'
INFO - Looking for bibtex format file 'refs.bib'
INFO - LaTeX decoding ...
INFO - Found BibTeX data source 'refs.bib'
```

And it returns with code `2` but displays no errors.

But there is no file generated! Can you help me figure out what is going on?

**Comment by plk** [comment]
can you turn on debug mode with the `--debug` option?

**Comment by jonsterling** [comment]
@plk Thanks, I think that was a good idea! Now I see the following very scary looking error:

```
Unicode::UCD: failed to find unicore/version in /var/folders/_r/lxw6q_r506s9g5wnn6l_j_tr0000gn/T/par-6a6f6e/cache-3a0ea40386c969a2af6106b56b3115f93636230f/inc/lib /var/folders/_r/lxw6q_r506s9g5wnn6l_j_tr0000gn/T/par-6a6f6e/cache-3a0ea40386c969a2af6106b56b3115f93636230f/inc CODE(0x7f8a380dbcd0) CODE(0x7f8a380dc2b8) at /var/folders/_r/lxw6q_r506s9g5wnn6l_j_tr0000gn/T/par-6a6f6e/cache-3a0ea40386c969a2af6106b56b3115f93636230f/inc/lib/Biber/Input/file/bibtex.pm line 1034.
```

I wonder if this is some problem specific to my machine.

**Comment by jonsterling** [comment]
OK, I killed biber's cache and it looks like it is working again 👍

**Comment by ViToni** [comment]
@plk Wondering if the failure `Unicode::UCD: failed to find unicore/version in ...` shouldn't be reported as such.
Otherwise the program exits with an error code but without any explanation. This led me down a rabbit hole for some hours...
It feels strange to have to let `biber` in debug mode to find an error.
Even better if the `biber` could suggest to clean the cache if it hits any cache problems.

**Long version**:
Spent some hours hunting down this issue (and solution). As I re-used an old LaTeX template initially everything worked fine. Later on I tried out different bibliography/citation styles and also used some random external `.bib` file (which turned out to be broken later on...) which didn't seem to work. Switching back to the old configuration didn't seem to help either.
After fixing and even reducing the `.bib` file to only two entries I still couldn't get `biber` to process it.

Clearing the biber cache clearly solved the issue for good (pun intended 🙂).
