### ISSUE TITLE
warnings when sorting on pages

### ISSUE THREAD

**Issue by cktai17** [plk/biber#353]
I have created a custom sorting scheme for biblatex that includes the field `pages` for sorting, but it gives a large amount of identical warnings. It seems excessive to me to provide a warning for every single entry when the "problem" lies with the sorting scheme. Perhaps this can be collected in a single warning?

So for example this:
```
\documentclass{article}
\usepackage[style=verbose, sorting=pages]{biblatex}
    \DeclareSortingScheme{pages}{
        \sort{
            \field{pages}
        }
    }
\bibliography{biblatex-examples}
\begin{document}
    \nocite{*}
    \printbibliography
\end{document}
```
gives 102 warnings that all state:
> WARN - Unknown field 'pages' found in sorting template

**Comment by plk** [comment]
You can't sort on `pages` as it's a "range" datatype. It contains the page range(s) of an item inside a larger collection (e.g. article in a journal). So, nobody has ever wanted to do this before. If you want a field that contains the total number of pages in an item, that would be a custom datamodel field specified as a non range datatype which you could sort on. However, the error isn't clear about this and I'll change it to something more informative.

**Comment by odomanov** [comment]
I have a similar problem with numbers/volumes etc. Journals sometimes publish double numbers/volumes numbered like 3-4. So I need to make these fields ranges. Is it possible to make them sortable? By the first number, for example.

**Comment by plk** [comment]
@odomanov - the problem is, what do we sort them as - integers or strings? Range fields can be ranges of either to accommodate things like "A-C" as well as "3-5". We can auto-detect ints but the problem is then all ranges in the bib have to be the same data type. Currently only things we know can only be ints are sorted as ints (some internal things like `citeorder` and date parts).

**Comment by odomanov** [comment]
I see, thank you. Actually, I can use `literal` instead of `range`, in most cases it sorts correctly. But the problem is that `\rangelen` fails even if `\iffieldnums` is true. I mean the following doesn't work (! Missing number, treated as zero.):
```latex
\iffieldnums{volume}
   {\ifnumcomp{\rangelen{volume}}{=}{2}
      {...}
      {...}%
  ...
```
Can I calculate the `rangelen` for the literal when I know that it is in fact range?

I'm sending the MWE if you need it.
[number-range.zip](https://github.com/plk/biber/files/11241333/number-range.zip)

**Comment by plk** [comment]
Not really as that is calculated by `biber` internally for range fields to allow for things like roman numerals in various encodings. However, you could use a sourcemap to extract the first number from the beginning of a range field, put it in some custom field and then sort on that? You could also force integer sorting for it by making sure that the `datatype` of the  custom field was "range", even though it only has one number in it.

**Comment by odomanov** [comment]
Thank you for the hint. The `Sourcemap` is working. Unfortunately I've managed to sort only Arabic numbers, but OK, it's enough so far. 

I actually don't want to make the custom field `range` because of those warnings that I'm trying to avoid.

**Comment by plk** [comment]
Hmm, what non-Arabic numbers are you trying to sort? As I remember, the transliteration interface is used to turn ranges into Arabic numerals for range size calculations - would be interested in being able to sort non-Arabic `int` fields too.

**Comment by odomanov** [comment]
Just to explain. I made `volume` to be `range`. Then I extract with regexp the first number from this range and put it to a custom field. Then I sort by this custom field. The custom field cannot be `range` because otherwise I have those warnings which I'm trying to avoid. So I made it `literal`. And then what I'm saying is that I know how to sort a `literal` field that contains Arabic numbers but I don't know how to sort it when it contains Roman numbers, for example (even if I manage to extract them from the initial range). So this is simply what I meant. 

But as I said for me it's enough -- I'm not sure I'll ever need to sort anything non-Arabic. But just if you happen to know some simple way, it would be nice to hear.

**Comment by cktai17** [comment]
> You can't sort on `pages` as it's a "range" datatype. It contains the page range(s) of an item inside a larger collection (e.g. article in a journal). So, nobody has ever wanted to do this before. If you want a field that contains the total number of pages in an item, that would be a custom datamodel field specified as a non range datatype which you could sort on. However, the error isn't clear about this and I'll change it to something more informative.

For what it's worth, what I wanted is for items to be sorted according to the first item of the range. So an article on page 503-510 is listed before an article on 550-590. The specific case I had was of an author who wrote multiple articles in the same journal in the same issue. These were then sorted according to the alphabetical order of titles when everything else was sorted chronological.

**Comment by cktai17** [comment]
Great, I'll try that, thanks!

**Comment by odomanov** [comment]
> You may be in luck - anything declared as datatype `integer` automatically detects roman numerals and converts them to arabic for internal sorting - you can try it ...

Ah, yes, thank you! I didn't realize that it could be `integer`. It really works.
