### ISSUE TITLE
Inconsistent behavior of "has DAY or ENDYEAR, cannot be output in legacy format"

### ISSUE THREAD

**Issue by bersbersbers** [plk/biber#354]
Check out this example:

```
# This entry works fine ...
echo @article{expected, month = {1}, day = {1}} > bug.bib

# ... while for this one, I get a "Date in entry 'bug' has DAY or ENDYEAR, cannot be output in legacy format."
echo @article{bug, year = {1970}, month = {1}, day = {1}}} >> bug.bib

biber --tool bug.bib --output-format=bibtex --output-legacy-date --O - | grep -v INFO
````

But `expected` also has a `DAY` and is output just fine:

```
WARN - Date in entry 'bug' has DAY or ENDYEAR, cannot be output in legacy format.
@ARTICLE{expected,
  DAY = {1},
  MONTH = {1},
}

@ARTICLE{bug,
  DATE = {1970-01-01},
}
```

My ideal solution would be to output `bug` with `YEAR = {1970}, DAY = {1}, MONTH = {1}`. I wouldn't even mind dropping the `DAY`. If that is indeed not possible, the behavior for `expected` should be modified and/or the warning message corrected.

**Comment by plk** [comment]
I think the issue here is that `DAY` is not a valid bibtex field in any normal entry and it's not therefore treated as a legacy element. Bibtex only has `YEAR` and `MONTH` by default. The warning is basically a data loss warning and `DAY` is not a valid date field and so can't be "lost", whereas as day in an ISO8601 date is a valid field and so can be lost ...
