### ISSUE TITLE
Biber on large inputs

### ISSUE THREAD

**Issue by mklss** [plk/biber#361]
I switched to Biber, because the features are nice. Unfortunately, it turned out almost unusably slow (>5 mins) on huge bib-files, e.g. [cryptobib](https://cryptobib.di.ens.fr/). I tried to work around this, by hacking yet another latex "fix". (A script, which produces a ".aux" compatible with bibtex, then runs bibexport to get only the relevant entries (this breaks aliases and probably more) and then runs latex/biber on this reduced dataset.)
However, this "fix" introduces a lot of overhead, inconveniences, and will probably cause problems in the long run. I'd prefer to avoid it.
Is there a good workflow for Biber with large files?

I guess/hope (knowing nothing about Biber/Perl) that it's possible to improve Biber's handling of large files relatively easily. 
Biber should be lazier: There is no need to "INFO - LaTeX decoding ..." *every* entry. (That's the part which takes the longest by far.) Only the (transitively) referenced ones are important. So, if Biber first gets rid of all irrelevant entries, and then does its work on that subset, this should speed up large file handling by a lot, and hardly affect small files. Perhaps, Biber could preprocess with a separate (fast) tool that does this? (The (only) difficulty I see lies in resolving aliases/crossrefs. Especially between different files.)

**Comment by plk** [comment]
Have you look at `biber`s tool mode? You can output (without tool mode) a subset of only referenced references also by using `--output-format=bibtex` and the other `--output-*` options which control the output details. This will give you a `.bib` file with only the referenced items.

`biber` can't really be speeded up internally much - I've already tuned it a lot. It has to decode everything into UTF-8 to make sure sorting works correctly and sorting itself is very complex and complete, taking a long time. `biber` does far more than `bibtex` does and so any comparison is fairly meaningless at this point.

**Comment by mklss** [comment]
Tool mode wouldn't solve the problem, it would just be a (probably better) replacement for bibexport. The "switch-bib-files-logic" of the script would still remain.[0] But I did not see an option, which exports just the entries referenced (in some .bcf file). If there is, and if it's faster than a full run of biber, wouldn't it be a useful addition to have this preprocess the input?

That biber does much more than bibtex is clear. That it will be slow(er) is expected (mostly due to Perl vs C). Nevertheless:
Does biber's sorting have to take into account entries which are not referenced? Does it have to UTF-8-decode everything[1], before picking out the referenced entries? If the answer to both is No, then I really expect that delaying UTF-8-decoding as long as possible should improve speed for sparsely used large inputs by a lot.[2]
That is first picking out the (transitively) referenced entries. Here no is used.  Now, discard all unreferenced entries. Finally, apply the full logic to this subset of data. In my use-case, this gets from 25MB to 20kB (plus a 300kB file with strings, which I did not resolve.
If so, then I see no way to speed things up. If not, why can't biber get rid of all entries, which do not need to be sorted, because they are not referenced?

Anyway, if you don't see a simple, manageable way to speed up processing large files, feel free to close this issue.
Also, thanks for your work!

[0] It's vitally important that compiling is as simple as possible. Optimally toolchain is supported by the editor. Otherwise, collaborating with other people gets very difficult. This setup is far from user-friendly and very fragile. It's a proof-of-concept.
[1] In particular, are names/keys/aliases which are UTF-8 encoded allowed? Do you promise to normalise such keys, so that different representations of the same string are correctly detected? Even if, normalised keys are just bytestrings with no real semantics. If I understand correctly, UTF-8 lexical comparisons are the expensive operations.
[2] How simple this is probably depends a lot on how the content is parsed.

**Comment by plk** [comment]
What people normally do is to use the full `.bib` on the first run but output `bibtex` format instead of `bbl` and that gives you a small `.bib` with only the referenced items which can be used on subsequent runs. This accords with the general policy that you can the archive the `.tex` and the new `.bib` and they are a self-contained unit to reproduce the document.
You do this by running `biber` with the `--output-format=bibtex` option (not tool mode).

`biber`'s sorting does not sort anything not referenced. However, it does preprocess every entry in the `.bib` to make it UTF8 first because the `btparse` library used is ancient and had to be modified to pass through glyphs properly. `btparse` and `bibtex` are famously bad at handling encodings and so we have to normalise everything into UTF-8 before entering the C routines for parsing. Another reason for this is because `.bib` files are often a horrible mess of things pasted from all over the place and in order to stand a chance of local-sensitive sorting, we have to ensure everything is in UTF-8. Unfortunately, this has to happen before parsing (and therefore reference selection) to make sure that the parsing library gives us something consistent and sensible.

**Comment by mklss** [comment]
Thanks for taking the time to answer and for the `--output-form=bibtex` option. In general, I guess, there's nothing short of a rewrite of `btparse` (and probably a lot more) you can do to speed things up, due to too much legacy and unpredictable use of .bib-files.
