### ISSUE TITLE
Overriding of settings in biber config file (tool mode)

### ISSUE THREAD

**Issue by alexreg** [plk/biber#372]
Would you consider making biber look at *both* user-specified (via the `--configfile` option) and default settings, with the former overriding the latter. It seems a bit cumbersome and inefficient to specify the great majority of the default settings all over again whenever I want to customise just one or two.

**Comment by plk** [comment]
Are you seeing some strange behaviour as this is already what should happen for the normal `--configfile` - you don't have to specify everything.

**Comment by alexreg** [comment]
Ah sorry, I didn't realise. The way I read the man page implied (to me) I needed to specify everything all over again. Let me try that.

**Comment by plk** [comment]
That's only for the tool-mode config file because there is no `.bcf` file in that case and therefore no defaults.

**Comment by alexreg** [comment]
So tool mode doesn't use the default `biber-tool.conf` file after all, if a custom one is specified as well?

**Comment by plk** [comment]
In tool mode, `biber-tool.conf` is used to set defaults because there is no `.bcf` but apart from that, it's the same and you can use the `--configfile` or command-line options to override the defaults.

**Comment by alexreg** [comment]
Oh, I see... that's where I was getting confused. I thought the default `biber-tool.conf` plus custom settings were used in 'normal' mode, whereas it's really just the settings derived from the `.bcf`, right? Whereas in tool mode, it's the default `biber-tool.conf` file plus (optionally) a user-provided conf file?

**Comment by plk** [comment]
Correct - `biber-tool.conf` is used instead of the `.bcf` in normal mode because there is no `.bcf` in tool mode. Then, the configfile and/or command-line arguments override either of these. However, some options are `biblatex` options which are passed to `biber` (via the `.bcf`) which is why in tool mode, you may need to use a custom `biber-tool.conf` because there are not configfile/command-line options to change the `biblatex` options. Examples are sorting templates, labelling templates etc.

**Comment by alexreg** [comment]
Thanks for the clarification!
