### ISSUE TITLE
normalization of ISBN

### ISSUE THREAD

**Issue by PeterMuellerr** [plk/biber#384]
A publisher lists “[Moderne Betriebssysteme](https://www.pearson.de/moderne-betriebssysteme-9783863267667)” with ISBN  978-3-8632-6766-7, whereas biber's normalization transforms it into 978-3-86326-766-7 (with langid={ngerman}).  Which one is correct™?

**Comment by moewew** [comment]
You'd think the publisher would know. The LoC agrees with Biber: https://www.loc.gov/publish/pcn/isbncnvt_pcn.html (insert the ISBN without hyphens and check "Hyphenate ISBNs"), so does DNB https://portal.dnb.de/opac/simpleSearch?query=9783863267667

If there is an issue with the ISBN I think this would have to be reported to the developers of the Perl library `Business::ISBN` that Biber uses to format ISBNs. Though I gather they get their data directly from the ISBN agency... So maybe you'd have to complain to them?

**Comment by PeterMuellerr** [comment]
I asked [Pearson](https://www.pearson.de/kontakt/kundenservice) yesterday. As for Perl, is the following code roughly what you have in mind?
```
#!/usr/bin/perl
use Business::ISBN;
$isbn=Business::ISBN->new('9783863267667')->as_string;
print "$isbn\n";
```
Or does any pre- or post-processing, perhaps in a language-dependent way, happen in biber or biblatex?

**Comment by moewew** [comment]
I don't really do Perl, but I tried your code and on my machine it gives `978-3-86326-766-7`, so I guess that it what I had in mind, yes.

Biber does

https://github.com/plk/biber/blob/4d643a5efd48312aaa9c9edb01d5916c5b307bab/lib/Biber/Input/file/bibtex.pm#L1068-L1100

so really just `$isbn->as_string`. I could not see any further post-processing on the Biber side (and I don't think there is, the `.bbl` file has `\field{isbn}{978-3-86326-766-7}` as produced by `as_string`) and the standard `biblatex` styles don't apply any post-processing on the LaTeX side either.

The bugtracker for `Business::ISBN` is at https://github.com/briandfoy/business-isbn/issues, but I don't know if this would be a considered an issue with `Business::ISBN` or maybe with the data `Business::ISBN::Data` which live at https://github.com/briandfoy/business-isbn-data. Keep in mind that the ISBN data do not come from `Business::ISBN::Data`, they can be obtained from https://www.isbn-international.org/range_file_generation# and it would probably be only a bug in `Business::ISBN::Data` if the data differ from what the ISBN agency has to say. I had a quick look at the PDF (last change 2021-07-08) you can download there and for `978-3` the PDF has the rule `85000-89999`, which squares with what `Business::ISBN` (and LoC and DNB) does (if I understand correctly).

This would suggest that the problem is not with `Business::ISBN`. The problem is either that Pearson does not format their ISBN according to the rules published by the ISBN agency or the data available from the ISBN agency is faulty.

**Comment by PeterMuellerr** [comment]
> I don't really do Perl,

You won't believe me, but the above was my first Perl program.

**Comment by PeterMuellerr** [comment]
> I don't really do Perl,

You won't believe me, but the above was my first Perl program. :-)

> This would suggest that the problem is not with `Business::ISBN`. The problem is either that Pearson does not format their ISBN according to the rules published by the ISBN agency or the data available from the ISBN agency is faulty.

Alright. We can file an issue at all three the Web pages you mentioned and then see what they have to say. Without filing issues, nothing happens at all, I'm afraid, as nobody will feel bothered by the discrepancy or perhaps even be aware of it.

Personally, I feel a bit uncomfortable to complain about stuff I've just learned and have myself no profound knowledge of. Would you perhaps like to take over from here?

**Comment by moewew** [comment]
Well, I don't know much more about these things than you (I just googled all these things) and I'm not even personally affected (and didn't already try to talk to Pearson), so I'd much rather you complained to them.

As mentioned previously, I really don't think `Business::ISBN` and `Business::ISBN::Data` are at fault here. They appear to get their data directly from the ISBN agency (https://www.isbn-international.org/content/about-us), so they would be the ones ultimately responsible for what you are seeing in Biber.

**Comment by PeterMuellerr** [comment]
Ok, thanks! 

Off-topic: For the moment, if you wish to have a great day, notice how the ISBN agency names its user manual: https://www.isbn-international.org/sites/default/files/ISBN%20International%20Users%20Manual%20-%207th%20edition_absolutely_final.docx

It's 7th edition and “absolutely final” :-)))))))))))))))))))).

**Comment by PeterMuellerr** [comment]
Small update as of 2021-07-27: International ISBN agency said it would contact German ISBN agency.

**Comment by briandfoy** [comment]
Here's what I said in the report in  briandfoy/business-isbn-data#10:

> Looking at the published ranges from https://www.isbn-international.org/range_file_generation, the Perl Business::ISBN module is correct. The ranges for the publisher codes are 7000-8499 and 85000-89999. There is no publisher code that is 8632 in the 3 group.

**Comment by briandfoy** [comment]
Also, you don't need to do any work to locate the distributed _RangeMessage.xml_ because `Business::ISBN::Data` already does that. If you want to use a different file, set `$ENV{ISBN_RANGE_MESSAGE}`. You don't need to do anything else there.

**Comment by moewew** [comment]
@briandfoy Thank you very much for replying also here. That squares with what I guessed above: The ISBN agency agrees with what `Business::ISBN` (and thus Biber) does. So Pearson are probably wrong (or the ISBN agency needs to update their data). In any case, there is nothing Biber can do here.

**Comment by PeterMuellerr** [comment]
Small update as of 2021-07-28: the International ISBN Agency said that the German ISBN Agency had contacted Pearson and that Pearson would look into it. As of 2021-07-29, the originally noticed discrepancy still exists even if it's not a problem of biber and the Perl modules.
@briandfoy Thank you for taking a look into it. The fact that some publishers apparently don't keep their ISBN clean and are thus o.k. with some loss of their of reputation is notable.

**Comment by PeterMuellerr** [comment]
Small update as of 2021-07-28: the International ISBN Agency said that the German ISBN Agency had contacted Pearson and that Pearson would look into it. As of 2021-07-29, the originally noticed discrepancy still exists even if it's not a problem of biber and the Perl modules.
@briandfoy Thank you for taking a look into it. The fact that some publishers apparently do not keep the ISBNs of their books in accordance with what their ISBN agency says is notable: after all, it incurs some loss of their of reputation and income.

**Comment by PeterMuellerr** [comment]
Pearson corrected it on https://www.pearson.de/moderne-betriebssysteme-9783863267667
