### ISSUE TITLE
Reference full list in xdata field

### ISSUE THREAD

**Issue by u-fischer** [plk/biber#387]
It seems as if there is no possibility to refer a full name (or literal) list from a xdata entry. One has to index the parts one by one. In the following example I would like to get both authors in citation 2 without having to list them like in citation 3. Would it be possible to extend the syntax? Either to change `author = {xdata=somenames-author},` to mean "all", or to add some wildcard syntax like `author = {xdata=somenames-author-*},`?

~~~~
\begin{filecontents*}[overwrite]{xdata-test.bib}
@XData{somenames,
author  ={Maria White and Julia Green},
location={Paris and London}
}

@book{somebook:a,
xdata  = {somenames},
title  = {All xdata}
}

@book{somebook:b,
author = {xdata=somenames-author},
title =  {Author=somenames-author}
}

@book{somebook:c,
author = {xdata=somenames-author-1 and xdata=somenames-author-2},
title  = {Author=somenames-author-1 and -2}
}
\end{filecontents*}
\documentclass{article}
\usepackage[sorting=none]{biblatex}
\addbibresource{xdata-test.bib}
\begin{document}
\nocite{somebook:a,somebook:b,somebook:c}
\printbibliography
\end{document}
~~~~

![image](https://user-images.githubusercontent.com/4047173/130997587-96d44f02-114d-4779-9c7a-cd4053116596.png)

**Comment by plk** [comment]
Please try biber 2.17 DEV from SourceForge. I have made it so that an index-less list reference splices in the whole list at the desired point so, for example, `xdata=somenames-author` now splices in all names in the AUTHOR list of the XDATA "somenames" entry rather than just the first one. I think this change is reasonable as the old behaviour is easy to get back by just appending "-1" to references.

**Comment by u-fischer** [comment]
This seems to work fine and imho it makes much more sense. Normally you want the full list.
