### ISSUE TITLE
biber freezes on Mac Catalina

### ISSUE THREAD

**Issue by ojmesa** [plk/biber#400]
Hi, I have a big latex file with a big database. I have been working on it for a long time without problems. I updated to the most recent version using Texlive. Since then, Biber freezes. It runs on a 100% CPU but keeps running for ever, with no message. In overleaf it works fine. Also, the same file runs with bibtex. There may be a problem with the binary for Mac Os X Catalina.

**Comment by plk** [comment]
Hmm, can you put the example somewhere to test? There have been a couple of updates to the sourceforge versions since the TL release as I tried to get M1 packaging for universal binaries working so you could also try the new universal binary on sourceforge: https://sourceforge.net/projects/biblatex-biber/files/biblatex-biber/current/binaries/MacOS/biber-darwin_universal.tar.gz/download

**Comment by plk** [comment]
Greetings, that's not so large if you can attache them to the ticket? Or put them on dropbox/onedrive etc.?

PK

**Comment by ojmesa** [comment]
To test please download 
the bib file 
https://drive.google.com/file/d/1H5kVpHTY34AgsrKcBkSwHzt-IH6zy0ZO/view?usp=sharing
and the bcf file
https://drive.google.com/file/d/1KKxARu0xs0oYZbes3u38yi1A15t9yAKG/view?usp=sharing
