### ISSUE TITLE
Biber exits silently

### ISSUE THREAD

**Issue by eddieschoute** [plk/biber#414]
When I run biber on my Red Hat desktop, seemingly nothing happens. No output is generated. It exits with code 255. It does create a folder `par-*` in `/tmp`. The binary `biber` in that folder, when I move it to my home, outputs the following
```
$ ./biber 
Usage: /home/eschoute/biber [ -Alib.par ] [ -Idir ] [ -Mmodule ] [ src.par ] [ program.pl ]
/home/eschoute/biber [ -B|-b ] [-Ooutfile] src.par
```
so I suppose that is working as expected.
I suspect one of the dependencies may be the issue. Any suggestions on how to debug this issue?

I installed biber through texlive. According to `tlmgr info biber` I have `cat-version: 2.17`.

**Comment by plk** [comment]
You can't move the `'biber` you find in the unpacked PAR cache anywhere - it won't work. You should first delete the cache (par-*) directory and then just run biber once which will take longer the first time as it unpacks everything. It should just output usage information without any arguments. But you need to wait until it exits normally on the first run so that if finished unpacking otherwise you'll have a broken installation and will need to delete the PAR cache.

**Comment by eddieschoute** [comment]
I get no output:
```
$ rm -r /tmp/par-657363686f757465/
$ biber
$ echo $?
255
```

**Comment by plk** [comment]
Hmm, that is odd. What happens if you download manually the new biber 2.18 from SF:

https://sourceforge.net/projects/biblatex-biber/files/biblatex-biber/current/binaries/Linux/

and just run that as a test?

**Comment by eddieschoute** [comment]
Indeed, `/tmp` seems to not allow executing binaries. I just get
```
bash: ./biber: Permission denied
```
for the biber binary in `/tmp/...`. I looked it up and found that my `/tmp` directory is mounted using `noexec`, that could explain why I cannot execute the binary.

**Comment by moewew** [comment]
Maybe https://github.com/plk/biber/issues/70 helps?

**Comment by eddieschoute** [comment]
`PAR_GLOBAL_TMP` doesn't seem to affect where biber extracts:
```
$ export PAR_GLOBAL_TMP=/home/eschoute/tmp/
$ echo $PAR_GLOBAL_TMP 
/home/eschoute/tmp/
$ biber
$ ls tmp
$
```
