### ISSUE TITLE
Add an option to avoid map of langid

### ISSUE THREAD

**Issue by bastien-roucaries** [plk/biber#420]
Hi

Polyglossia support BCP47 therefore it will be nice to add an option in order to avoid the reverse map
https://github.com/plk/biber/blob/402e3d229e75c0502af83cfcf628eccb8527b207/lib/Biber/Input/file/bibtex.pm#L1109

**Comment by plk** [comment]
That comment is a bit misleading in the code, I will correct it. Quite a lot depend on `langid` currently and I don't think we can switch to bcp47 inside `biblatex.sty` without some changes there since `\.lbx` files are not bcp47 named (there was a push to do this quite some time ago but it never went anywhere). I suspect it will be more pressing if/when `babel` moves to bcp47 too.
