### ISSUE TITLE
Provide releases on GitHub

### ISSUE THREAD

**Issue by mikefarmer01** [plk/biber#423]
Biber releases should be provided here on GitHub.

Would make it easier to set up "packaging" of Biber with [Scoop](https://scoop.sh)

**Comment by josephwright** [comment]
I'm probably missing something: why would a tool like that be of relevance? End users should be getting Biber from TeX Live or MiKTeX, and they have well-established workflows.

**Comment by plk** [comment]
I thought the same when I looked - I can't imagine anyone would install `biber` as a stand-alone tool outside of TexLive or MikTeX. However, there should be releases on Github, just for general consistency and I had forgotten to take the 2.18 release out of draft so thanks for the reminder - that's done now.

**Comment by kolewu** [comment]
I do use the direct download of the release from Sourceforge for building a docker container. Since the container is based on openSUSE and the TeXLive packaging of this distro is "annoying" (to say the least), I opted for directly downloading the biber binary to save the weird texlive packaging dependencies and 30 MB of additional downloads.

Since the sourceforge download has no versioned URL for the latest version, I was hoping a github release would offer that as an option.

**Comment by plk** [comment]
As long as you want the perl-source version rather than a binary, then the github release should be fine.
