### ISSUE TITLE
biber sourcemapping - PCRE regexp with Unicode support

### ISSUE THREAD

**Issue by matteofg** [plk/biber#483]
It also required on [TeX.SE](https://tex.stackexchange.com/questions/725183/biber-sourcemapping-pcre-regexp-with-unicode-support)

I need to match an Unicode character belonging to the “uppercase letter” category with `\p{Lu}`.

```
\begin{filecontents}[overwrite]{\jobname.bib}
@article{doe,
  author = {Doe, John},
  title = {Title of the ArticlĒ}, %final uppercase letter
  subtitle = {Subtitle of the Article},
  journaltitle = {Title of the Journal},
  date = {2023},
}
\end{filecontents}

\documentclass{article}
\usepackage[style=verbose]{biblatex}
\addbibresource{\jobname.bib}

\DeclareStyleSourcemap{
  \maps{
    \map{
      % add \@ at the final uppercase letter (if present)
      \step[fieldsource=title, match=\regexp{(\p{Lu})\Z}, replace={$1\string\\@}]
    }
  }
}

\begin{document}
\cite{doe}
\printbibliography
\end{document}
```

From what I [read](https://www.regular-expressions.info/pcre.html#supportucp), by default, PCRE compiles without Unicode support.

Is it possible to do something on the biber/biblatex side?

**Comment by plk** [comment]
The engine is full Unicode (it's perl, not just PCRE ...). The issue was a somewhat obscure NFD/NFC form problem. Character classes like "\p{Lu}" operate on characters, not glyphs and so when things are in NFD form (like the biber internals are), character classes like these won't reliably match NFD forms as these are often multi-character glyphs. Should be fixes in biber 2.21 DEV version which you can get from sourceforge in the development folder.

**Comment by matteofg** [comment]
Thank's, biber 2.21 DEV works fine!

However, as answered on [TeX.SE](https://tex.stackexchange.com/a/725294/287680), just replace `\p{Lu}` with `\p{Lu}\p{M}*`.

The problem arose from my ignorance about the Unicode encoding and the correct regexp syntax. So I wonder: does it make sense to change the biber code?

**Comment by plk** [comment]
Yes, I will revert that fix as it's cleaner to leave everything internally in NFD.
