### ISSUE TITLE
Wrong sorting with sortlocale = nn_NO

### ISSUE THREAD

**Issue by SverreStausland** [plk/biber#81]
Cf. http://tex.stackexchange.com/questions/263900/sortlocale-no-longer-works-with-current-versions-of-biblatex-and-biber

If this is fixed with the next version of biber (v.2.2), when will it be released through CTAN & texlive? I'm in a bit of a jam because of this, as I have an upcoming deadline to submit the final ready-to-print version of paper.

**Comment by plk** [comment]
Can you download biber 2.2 and try it? I have no release date for 2.2 yet.

**Comment by u-fischer** [comment]
I tried with biber 2.2. and the problem was gone. You can download it from here https://sourceforge.net/projects/biblatex-biber/files/biblatex-biber/development/binaries/
On windows you can unpack the biber-MSwin.zip. Rename (if you want) the biber.exe to e.g. biber22.exe, copy it to some folder in your path and then use biber22 instead of biber in your editor.

**Comment by SverreStausland** [comment]
Thanks for the guide, Ulrike (which I needed). The bibliography is
correctly sorted with biber 2.2.
