### ISSUE TITLE
Biber processes URL field

### ISSUE THREAD

**Issue by moewew** [plk/biber#92]
This is a bug report on behalf of [Link to a Web page works inside the main document but not in the bibliography](http://tex.stackexchange.com/q/278258/).

Consider the following MWE
```
\documentclass{article}
\usepackage[T1]{fontenc}
\usepackage[utf8]{inputenc}
\usepackage{filecontents}
\usepackage[backend=biber]{biblatex}
\usepackage{hyperref}

\begin{filecontents}{\jobname.bib}
@online{elk,
    title={Towards a Unified Theory on Brontosauruses},
    author={Anne Elk},
    year=2014,
    url={http://example.com/Elk%E2%80%99Bronto%20},
    urldate={2015-10},
}
\end{filecontents}
\addbibresource{\jobname.bib}

\begin{document}
\url{http://example.com/Elk%E2%80%99Bronto%20}

\nocite{*}
\printbibliography
\end{document}
```

While the input in both cases is the same, the actual output of the URL in the document differs.
The in-document URL shows as
> http://example.com/Elk%E2%80%99Bronto%20

while the in-bibliography URL shows as 
>   http://example.com/Elk%C3%A2%C2%80%C2%99Bronto

It seems that Biber does some processing of the URL field.

**Comment by plk** [comment]
Biber uses some standard URL encoding library to do this but this is strange, I will check.

**Comment by johannesbottcher** [comment]
In september i stumbled upon the url encoding as well, but did not investigate further because something else got on the stack of things to do. 

```syntax=latex
\documentclass{article}
\usepackage[utf8]{inputenc}
\usepackage[T1]{fontenc}
\usepackage{biblatex}
\addbibresource{\jobname.bib}
\usepackage{filecontents}
\begin{filecontents}{\jobname.bib}
	@article{ss,
		url={ß},
	}
\end{filecontents}
\begin{document}
\nocite{*}
\url{ß}
\printbibliography
\end{document}
```

According to wikipedia, the urlencoding gives back the encoding of the charackter as an utf8 encoded sequence, whereas it seems what biber returns is something which is not treated as utf8. 
I realy didn't follow up on this, but is it possible that what biber returns in the example above are the codepoints of the signs returned by `\url`?

**Comment by plk** [comment]
Please try DEV version 2.3 from Sourceforge anyway - there were some strange things going on in the encoding which seem unnecessary.

**Comment by moewew** [comment]
The URL encoding works as expected now. Thank you very much for the swift response.
